### ISSUE TITLE
Include issue

### ISSUE THREAD

**Issue by smolskyaleksey** [VoIPGRID/VialerSIPLib#10]
[PJTEST.zip](https://github.com/VoIPGRID/VialerSIPLib/files/569124/PJTEST.zip)

Hi everyone. I added Pod to my project and try to build and i have issue 
http://prntscr.com/d2ksx7

Expected function body after function declarator 

```
#if defined(PJ_HAS_STRING_H) && PJ_HAS_STRING_H != 0
#   include <string.h>
#else

    PJ_DECL(int) strcasecmp(const char *s1, const char *s2);
    PJ_DECL(int) strncasecmp(const char *s1, const char *s2, int len);

#endif
```

![2016-11-03 16 36 36](https://cloud.githubusercontent.com/assets/6605765/19968014/bc38abe2-a1e3-11e6-8cbd-9348ffb2ef46.png)

I have cocoapods 1.1.1 and XCode 8.1
How can I resolve it?

I provide demo project to show error
![2016-11-03 16 39 43](https://cloud.githubusercontent.com/assets/6605765/19968104/2ba91174-a1e4-11e6-974b-44614c3ceacc.png)

**Comment by bobvoorneveld** [comment]
Hi there,

Have you tried to run it without any other pods installed? It might conflict with some of the pods you have installed already?

**Comment by smolskyaleksey** [comment]
@bobvoorneveld if you install without any other pods you will not get issue. I have conflict with another  pods.

**Comment by bobvoorneveld** [comment]
Without looking into your other pods, my guess is that one of the pods is declaring the same kind of function headers that interfere with the pjsip library. Try to find a solution that will not use that pod or will not use the same function headers.

**Comment by smolskyaleksey** [comment]
Could you help me to find solution?

**Comment by bobvoorneveld** [comment]
Is there a reason why you include LibFortuna? I think that that pod might raise the issue, because it is including string.h and pjsip is including it. Try to find a way that it isn't including string.h. I'm no expert in c++ code, so you might need some assistance from SO...
