### ISSUE TITLE
Account registration failed

### ISSUE THREAD

**Issue by kongfanwu** [VoIPGRID/VialerSIPLib#102]
Configuration is as follows. thanks!

Keys.swift file
struct Keys {
    struct SIP {
        static let Account = "102"
        static let Password = "1234"
        static let Domain = "192.168.199.194"
        static let Proxy = "16"
    }
    static let NumberToCall = "102"
}

log
CoreFoundation = 1290.110000
Could not match CoreFoundation = 1290.110000
DEBUG   18:45:59.020 [VSLEndpoint -[VSLEndpoint startEndpointWithEndpointConfiguration:error:]:125] Creating new PJSIP Endpoint instance.
18:45:59.034 os_core_unix.c !pjlib 2.6 for POSIX initialized
18:45:59.038 sip_endpoint.c  .Creating endpoint instance...
18:45:59.041          pjlib  .select() I/O Queue created (0x13d085e28)
18:45:59.041 sip_endpoint.c  .Module "mod-msg-print" registered
18:45:59.041 sip_transport.  .Transport manager created.
18:45:59.041   pjsua_core.c  .PJSUA state changed: NULL --> CREATED
INFO    18:45:59.183 [VSLEndpoint void logCallBack(int, const char *, int):451]   pjsua_core.c  .pjsua version 2.6 for iPhone OS-9.3.2/arm-iPhone7,1/iOS-SDK initialized
INFO    18:45:59.187 [VSLEndpoint -[VSLEndpoint startEndpointWithEndpointConfiguration:error:]:233] PJSIP Endpoint started succesfully
INFO    18:45:59.190 [VSLAccount -[VSLAccount configureWithAccountConfiguration:error:]:136] Account added succesfully
DEBUG   18:46:09.011 [VSLAccount -[VSLAccount registerAccountWithCompletion:]:169] Account valid: YES
VERBOSE 18:46:09.013 [VSLAccount -[VSLAccount registerAccountWithCompletion:]:179] Sending registration for account: 0
INFO    18:46:09.024 [VSLEndpoint void logCallBack(int, const char *, int):451] tsx0x13d8b74a8  ..Failed to send Request msg REGISTER/cseq=10699 (tdta0x13d0edc00)! err=120065 (No route to host)
WARNING 18:46:09.025 [VSLEndpoint void logCallBack(int, const char *, int):448]    pjsua_acc.c  ....SIP registration failed, status=503 (No route to host)
VERBOSE 18:46:09.027 [VSLEndpoint void onRegState2(pjsua_acc_id, pjsua_reg_info *):514] onRegState2
DEBUG   18:46:09.028 [VSLAccount -[VSLAccount setAccountState:]:54] AccountState will change from VSLAccountStateOffline(0) to VSLAccountStateDisconnected(3)
ERROR   18:46:09.055 [VSLEndpoint void logCallBack(int, const char *, int):445]    pjsua_acc.c  .Unable to create/send REGISTER: No route to host [status=120065]
### # **ERROR   18:46:09.056 [VSLAccount -[VSLAccount registerAccountWithCompletion:]:186] Account registration failed**
---------- %@ Optional(Error Domain=VialerSIPLib.VSLAccount Code=2 "Account registration failed" UserInfo={NSLocalizedDescription=Account registration failed, NSLocalizedFailureReason=PJSIP status code: 120065})
INFO    18:46:11.444 [VSLEndpoint void logCallBack(int, const char *, int):451] tsx0x13d8beea8 !..Failed to send Request msg REGISTER/cseq=29318 (tdta0x13d8bce00)! err=120065 (No route to host)
WARNING 18:46:11.446 [VSLEndpoint void logCallBack(int, const char *, int):448]    pjsua_acc.c  ....SIP registration failed, status=503 (No route to host)
INFO    18:46:11.448 [VSLEndpoint void logCallBack(int, const char *, int):451]   pjsua_call.c  .....Invalid call_id 0 in pjsua_call_hangup()
INFO    18:46:11.450 [VSLEndpoint void logCallBack(int, const char *, int):451]   pjsua_call.c  .....Invalid call_id 1 in pjsua_call_hangup()
INFO    18:46:11.451 [VSLEndpoint void logCallBack(int, const char *, int):451]   pjsua_call.c  .....Invalid call_id 2 in pjsua_call_hangup()
INFO    18:46:11.453 [VSLEndpoint void logCallBack(int, const char *, int):451]   pjsua_call.c  .....Invalid call_id 3 in pjsua_call_hangup()
INFO    18:46:11.455 [VSLEndpoint void logCallBack(int, const char *, int):451]    pjsua_acc.c  ....Disconnecting 4 call(s) of account #0 after reregistration attempt failed
VERBOSE 18:46:11.456 [VSLEndpoint void onRegState2(pjsua_acc_id, pjsua_reg_info *):514] onRegState2
ERROR   18:46:11.458 [VSLEndpoint void logCallBack(int, const char *, int):445]    pjsua_acc.c  .Unable to create/send REGISTER: No route to host [status=120065]
INFO    18:46:11.460 [VSLEndpoint void logCallBack(int, const char *, int):451]   pjsua_call.c  .Invalid call_id 0 in pjsua_call_hangup()
INFO    18:46:11.461 [VSLEndpoint void logCallBack(int, const char *, int):451]   pjsua_call.c  .Invalid call_id 1 in pjsua_call_hangup()
INFO    18:46:11.462 [VSLEndpoint void logCallBack(int, const char *, int):451]   pjsua_call.c  .Invalid call_id 2 in pjsua_call_hangup()
INFO    18:46:11.462 [VSLEndpoint void logCallBack(int, const char *, int):451]   pjsua_call.c  .Invalid call_id 3 in pjsua_call_hangup()
INFO    18:46:11.463 [VSLEndpoint void logCallBack(int, const char *, int):451]    pjsua_acc.c  Disconnecting 4 call(s) of account #0 after reregistration attempt failed

**Comment by spindleredmer** [comment]
Your proxy address is 16 which looks incorrect to me.
`ERROR 18:46:09.055 [VSLEndpoint void logCallBack(int, const char *, int):445] pjsua_acc.c .Unable to create/send REGISTER: No route to host [status=120065]`

**Comment by bkr1989** [comment]
Hi @redmerloen ..actually proxy is not required in our scenario ... if i pass nil proxy  its showing an error and crashing.. is there any way to handle this...

**Comment by redmerloen** [comment]
Thank you will, fix the issue when proxy is nill

**Comment by redmerloen** [comment]
I think this issue is fixed.
