### ISSUE TITLE
Enable TURN configuration

### ISSUE THREAD

**Issue by gierunio** [VoIPGRID/VialerSIPLib#103]
### Version
2.7.0

### File / Feature
VSLAccount.m

### Expected behaviour
I have been struggling with NAT connection and I would like to change some properties in TURN configuration without modifying VSLAccount class. I've tested following code inserted into `configureWithAccountConfiguration:error:`, before `int accountId;` line:

```
acc_cfg.allow_contact_rewrite = 0;
acc_cfg.contact_rewrite_method = 0;
acc_cfg.contact_use_src_port = 0;
acc_cfg.allow_via_rewrite = 0;
    
acc_cfg.turn_cfg_use = PJSUA_TURN_CONFIG_USE_CUSTOM;
acc_cfg.turn_cfg.enable_turn = 1;
acc_cfg.turn_cfg.turn_server = pj_str("turn.sever");
acc_cfg.turn_cfg.turn_auth_cred.data.static_cred.username = pj_str("turn.username");
acc_cfg.turn_cfg.turn_auth_cred.data.static_cred.data_type = PJ_STUN_PASSWD_PLAIN;
acc_cfg.turn_cfg.turn_auth_cred.data.static_cred.data = pj_str("turn.password");
```

1. May I call `configureWithAccountConfiguration:error:` after the account has been configured once (in VialerSIPLib's `createAccountWithSipUser:error:` method)?
2. Could there be more properties in VLSAccountConfiguration so that more params could be customized?

**Comment by spindleredmer** [comment]
I think the best fix is to add a VSLStunConfiguration class. Where it would be possible to configure your stun settings.

**Comment by gierunio** [comment]
I added VSLTurnConfiguration and VSLIceConfiguration classes and attached them to the VSLAccountConfiguration. Seems ok.

**Comment by spindleredmer** [comment]
Could you create a pull request for your fix?

**Comment by gierunio** [comment]
I guess it's solved.
