### ISSUE TITLE
Unregister Account after hangup call

### ISSUE THREAD

**Issue by mital87** [VoIPGRID/VialerSIPLib#104]
@spindleredmer  & @bobvoorneveld: I have updated **VialerSIPLib Pod (2.7.0 -> 2.8.0).**  I am calling **Account A** to **Account B.** **Account B** successfully receive the incoming call. Call connection has been successfully established.  Now **Account B** disconnect the call. Both the **Accounts (A & B)** are automatically unregistered. Please help me, how can I fix this issue?

**Comment by spindleredmer** [comment]
That is correct I changed that in version 2.8.0. A bit of cleanup after a call has been made. Will see to see if I can make this optional. If you don't want to unregister the account after a call has been made.

**Comment by mital87** [comment]
If you do that, It would be great for us. Thanking You.
