### ISSUE TITLE
Data usage

### ISSUE THREAD

**Issue by masiiha** [VoIPGRID/VialerSIPLib#108]
@spindleredmer 
Hello
Data usage is now 1 megabyte per minute
Can it be less?

**Comment by spindleredmer** [comment]
Do you use iLBC as the preferred codec?
because iLBC only uses 150 KB for 1 minute of call
after the the configureEndpoint do
`VialerSIPLib.sharedInstance().onlyUseIlbc(true)` for swift or 
`[[VialerSIPLib sharedInstance] onlyUseIlbc:YES];` for objective c

**Comment by masiiha** [comment]
@spindleredmer 
Thanks for your guidance
Do you have ideas for using opus codecs?
