### ISSUE TITLE
Exceeded number of ports when entering/leaving a conversation multiple times

### ISSUE THREAD

**Issue by gierunio** [VoIPGRID/VialerSIPLib#109]
### Version

2.8.0

### File / Feature

VSLRingback.m

### Actual behaviour

The app crashes due to failure assertion.

### Stacktrace / Error message

Error:
`Assertion failed: (!"Too many ports"), function pjmedia_conf_add_port, file ../src/pjmedia/conference.c, line 766.`

Raised from VSLRingback.m, line 64:

`status = pjsua_conf_add_port(endpoint.pjPool, [self ringbackPort], (int *)&_ringbackSlot);`

Full stacktrace:

- 2   libsystem_c.dylib                   0x0000000183e9cfb8 abort + 140,
- 3   libsystem_c.dylib                   0x0000000183e70a9c basename_r + 0,
- 4   VialerSIP                           0x00000001036cef0c pjmedia_conf_add_port + 360,
- 5   VialerSIP                           0x00000001037ce004 pjsua_conf_add_port + 72,
- 6   VialerSIP                           0x000000010367c828 -[VSLRingback init] + 888,
- 7   VialerSIP                           0x00000001036675b0 -[VSLCall ringback] + 96,
- 8   VialerSIP                           0x0000000103668c3c -[VSLCall mediaStateChanged:] + 672,
- 9   VialerSIP                           0x0000000103676888 onCallMediaState + 468,
- 10  VialerSIP                           0x00000001037a9970 pjsua_call_on_media_update + 524,
- 11  VialerSIP                           0x000000010377decc inv_negotiate_sdp + 268,
- 12  VialerSIP                           0x000000010377dc30 inv_check_sdp_in_incoming_msg + 1620,
- 13  VialerSIP                           0x000000010377e6cc inv_on_state_calling + 704,
- 14  VialerSIP                           0x000000010377d4c0 mod_inv_on_tsx_state + 116,
- 15  VialerSIP                           0x00000001036b9448 pjsip_dlg_on_tsx_state + 244,
- 16  VialerSIP                           0x00000001036bb7d4 mod_ua_on_tsx_state + 88,
- 17  VialerSIP                           0x00000001036afa68 tsx_set_state + 712,
- 18  VialerSIP                           0x00000001036b1718 tsx_on_state_proceeding_uac + 596,
- 19  VialerSIP                           0x00000001036b028c pjsip_tsx_recv_msg + 232,
- 20  VialerSIP                           0x00000001036b0ce4 mod_tsx_layer_on_rx_response + 236,
- 21  VialerSIP                           0x0000000103691dbc pjsip_endpt_process_rx_data + 724,
- 22  VialerSIP                           0x00000001036912d0 endpt_on_rx_msg + 576,
- 23  VialerSIP                           0x000000010369c8e8 pjsip_tpmgr_receive_packet + 1872,
- 24  VialerSIP                           0x000000010369f790 udp_on_read_complete + 272,
- 25  VialerSIP                           0x0000000103809c68 ioqueue_dispatch_read_event + 976,
- 26  VialerSIP                           0x000000010380c7a4 pj_ioqueue_poll + 1268,
- 27  VialerSIP                           0x00000001036918b8 pjsip_endpt_handle_events2 + 360,
- 28  VialerSIP                           0x00000001037b77d4 pjsua_handle_events + 72,
- 29  VialerSIP                           0x00000001037b6cb8 worker_thread + 52,
- 30  VialerSIP                           0x000000010380ec20 thread_main + 188,
- 31  libsystem_pthread.dylib             0x000000018404031c <redacted> + 308,
- 32  libsystem_pthread.dylib             0x00000001840401e8 <redacted> + 0,
- 33  libsystem_pthread.dylib             0x000000018403ec28 thread_start + 4

**Comment by gierunio** [comment]
When I leave the conversation, I call `hangout` method on VSLCall and then nil it (I assume the only reference remains in VSLCallManager and eventually gets destroyed), and `remove` method on VSLAccount (I create an account each time I join the conversation). Is there another cleanup step I should consider?

**Comment by redmerloen** [comment]
Thank you for this bug report.
I will try to figure out why the Ports are not correctly closed

**Comment by tomaszkoperski** [comment]
Any news in that regard?

**Comment by redmerloen** [comment]
There has been some improvements in the VSLRingback code, can you see if this is still an issue?
