### ISSUE TITLE
how can I know that my account communicate with server or not?

### ISSUE THREAD

**Issue by mital87** [VoIPGRID/VialerSIPLib#110]
@spindleredmer: how can I know that my account communicates with the server or not? 

Suppose, I have successfully registered with **Account A.** Now, I have disabled my Internet connection from my **iOS device.** so how can I know that my **Account A** has still registered on the server or not? Is there any **property or method** available to know its status?

**Comment by redmerloen** [comment]
There are a couple of properties on VSLAccount you can check if an account is still valid of a registration
```
/**
 *  The current SIP registration status code.
 */
@property (readonly, nonatomic) NSInteger registrationStatus;

/**
 *  A Boolean value indicating whether the account is registered.
 */
@property (readonly, nonatomic) BOOL isRegistered;

/**
 *  An up to date expiration interval for the account registration session.
 */
@property (readonly, nonatomic) NSInteger registrationExpiresTime;
```

**Comment by mital87** [comment]
@redmerloen: I have agreed with you for above properties. But When I have registered successfully on the server & my internet connection is lost that time i have got bellow status of my account:

registration status: connected
isRegistered: true

so, how can I get the valid & accurate value of my account? Please help me to resolve my issue.

Thanking You.
