### ISSUE TITLE
No audio is transferred when answering a call 

### ISSUE THREAD

**Issue by maxkomarychev** [VoIPGRID/VialerSIPLib#111]
Hi, I noticed quite strange behavior in the lib after incoming call is answered: there is no rtp (or any other) traffic to the audio host:port advertised by caller in his INVITE.
Did anyone else notice this?

I also experimented with Telephone a bit and it works fine. Even more - our SIP logs captured by wireshark are *identical*, yet vialer doesn't send audio. As a result it can't receive audio as well (apparently freeswitch is waiting for a first rtp packet to came in in order to adjust routing properly which never happens).

There are also no streams if you explore logs with wireshark's "Telephony => VoIP calls => Play streams".
Everything works fine when calling side is vialer lib.

Any ideas? Hints?
Thanks

**Comment by redmerloen** [comment]
I have noticed this issue, on the newest version of the Vialer-pjsip-iOS. When switching network this also happens. Will investigate it.

**Comment by maxkomarychev** [comment]
@redmerloen oh sorry, I figured it out some time ago. The original issue was related to the bugs in host app and misuse of VialerSIPLib api. Audio session wasn't properly managed.
You can close this.

**Comment by maxkomarychev** [comment]
I'll close it since my case was clearly not related to bug in pjsip or vialer lib.
