### ISSUE TITLE
hello 51 error after update

### ISSUE THREAD

**Issue by masiiha** [VoIPGRID/VialerSIPLib#118]
d: warning: ignoring file /Users/newuser/Downloads/VialerSIPLib-develop/Example/Pods/Vialer-pjsip-iOS/VialerPJSIP.framework/VialerPJSIP, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): /Users/newuser/Downloads/VialerSIPLib-develop/Example/Pods/Vialer-pjsip-iOS/VialerPJSIP.framework/VialerPJSIP

**Comment by redmerloen** [comment]
yeah there is something missing in the newest version am fixing it as we speak. the Simulator linking is missing
