### ISSUE TITLE
Compare issue

### ISSUE THREAD

**Issue by smolskyaleksey** [VoIPGRID/VialerSIPLib#12]
``` obj-c
- (VSLAccount *)getAccountWithSipAccount:(NSString *)sipAccount {
    for (VSLAccount *account in self.accounts) {
        if (account.accountConfiguration.sipAccount == sipAccount) {
            return account;
        }
    }
    return nil;
}
```

Why do not you use the method isEqualToString?

**Comment by bobvoorneveld** [comment]
Good question, and probably better if we would do a isEqualToString. Would you like to file a PR so that we can merge that into the project?

**Comment by smolskyaleksey** [comment]
I don't have permission for repo.

**Comment by bobvoorneveld** [comment]
Check:
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by smolskyaleksey** [comment]
Done:
https://github.com/VoIPGRID/VialerSIPLib/pull/13

**Comment by bobvoorneveld** [comment]
Accepted #13
