### ISSUE TITLE
Call is disconnecting

### ISSUE THREAD

**Issue by attiqueullah** [VoIPGRID/VialerSIPLib#120]
### Version

{version or tag here}

### File / Feature

{file or feature containing the issue}

### Expected behaviour

{what should happen}

### Actual behaviour

{what happens}

### Stacktrace / Error message

{paste here}

### Other info

{anything else that might be related/useful}

**Comment by attiqueullah** [comment]
My registeration is working successfully but when i am going to call a number it disconnected after sometime here is the log of error 
💜 VERBOSE 17:39:35.124 [VSLEndpoint void onCallState(pjsua_call_id, pjsip_event *):473] onCallState
💚 DEBUG   17:39:35.135 [VSLCall -[VSLCall setCallState:]:112] Call(820CB14C-B24C-432C-AC40-9A0F40A077B3). CallState will change from VSLCallStateCalling(1) to VSLCallStateDisconnected(6)
❗ ERROR   17:39:35.151 [VSLCall -[VSLCall calculateStats]:662] Stream is not active!
❗ ERROR   17:39:35.153 [VSLCallStats -[VSLCallStats generate]:213] Stream is not active!
💜 VERBOSE 17:39:35.168 [VSLCallManager -[VSLCallManager removeCall:]:211] Call(820CB14C-B24C-432C-AC40-9A0F40A077B3) removed. Calls count: 0
💚 DEBUG   17:39:35.168 [CallKitProviderDelegate -[CallKitProviderDelegate callStateChanged:]:293] Call never connected, in DISCONNECTED state, with UUID: 820CB14C-B24C-432C-AC40-9A0F40A077B3
💜 VERBOSE 17:39:35.170 [VSLEndpoint -[VSLEndpoint stopNetworkMonitoring]:662] No active calls for any account, stopping network monitor
💚 DEBUG   17:39:35.182 [VSLEndpoint void logCallBack(int, const char *, int):464]          pjsua_media.c  .....Call 0: deinitializing media..
💚 DEBUG   17:39:35.182 [VSLEndpoint void logCallBack(int, const char *, int):464]          pjsua_media.c  ......Call 0: cleaning up provisional media, prov_med_cnt=2, med_cnt=0
💚 DEBUG   17:39:35.387 [VSLEndpoint void logCallBack(int, const char *, int):464]           pjsua_core.c  .RX 504 bytes Response msg 488/INVITE/cseq=9113 (rdata0x15c0b3028) from UDP 103.36.147.66:5060:
SIP/2.0 488 Not acceptable here

Via: SIP/2.0/UDP 192.168.10.2:6875;branch=z9hG4bKPjCUKmAHkUNNAsLWtxsemq.UxbKUgLUjGb;received=39.53.60.254;rport=6875

From: sip:9009053@Voice.wantok.vu;tag=w5qqjSR0z1qdteW99NQ-G6q7mk3UhcEu

To: sip:9009054@Voice.wantok.vu;tag=as5fc71278

Call-ID: Q3FACKvdRx-TewqPsLxUicvy4AUPEO6I

CSeq: 9113 INVITE

Server: FPBX-2.11.0(11.22.0)

Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE

Supported: replaces, timer

Content-Length: 0




--end msg--
💚 DEBUG   17:39:35.388 [VSLEndpoint void logCallBack(int, const char *, int):464]           pjsua_core.c  ..TX 384 bytes Request msg ACK/cseq=9113 (tdta0x15c065ca8) to UDP 103.36.147.66:5060:
ACK sip:9009054@Voice.wantok.vu SIP/2.0

Via: SIP/2.0/UDP 39.53.60.254:6875;rport;branch=z9hG4bKPjCUKmAHkUNNAsLWtxsemq.UxbKUgLUjGb

Max-Forwards: 70

From: sip:9009053@Voice.wantok.vu;tag=w5qqjSR0z1qdteW99NQ-G6q7mk3UhcEu

To: sip:9009054@Voice.wantok.vu;tag=as5fc71278

Call-ID: Q3FACKvdRx-TewqPsLxUicvy4AUPEO6I

CSeq: 9113 ACK

Route: <sip:Voice.wantok.vu;lr>

Content-Length:  0




--end msg--
💚 DEBUG   17:39:36.187 [VSLEndpoint void logCallBack(int, const char *, int):464]            pjsua_aud.c  Closing sound device after idle for 1 second(s)
💚 DEBUG   17:39:36.852 [VSLEndpoint void logCallBack(int, const char *, int):464]            pjsua_aud.c  .Closing iPhone IO device sound playback device and iPhone IO device sound capture device
💚 DEBUG   17:39:36.875 [VSLEndpoint void logCallBack(int, const char *, int):464]        coreaudio_dev.c  .core audio stream stopped
💚 DEBUG   17:39:36.875 [VSLAudioController -[VSLAudioController deactivateAudioSession]:101] Deactivating audiosession
💜 VERBOSE 17:39:40.353 [VSLCall -[VSLCall dealloc]:103] Dealloc Call uuid:820CB14C-B24C-432C-AC40-9A0F40A077B3 id:0

There is some sort of error like this 
❗ ERROR   17:39:35.151 [VSLCall -[VSLCall calculateStats]:662] Stream is not active!
❗ ERROR   17:39:35.153 [VSLCallStats -[VSLCallStats generate]:213] Stream is not active!
Please help me in this regard . Thanks

**Comment by attiqueullah** [comment]
I have resolved the issue . Thanks

**Comment by davejefferies** [comment]
How did you resolve the issue?  I am having the same issue

**Comment by TheEngineerz** [comment]
@attiqueullah  how did you resolve the issue . @davejefferies any progress?

**Comment by redmerloen** [comment]
`SIP/2.0 488 Not acceptable here`
Means something is incompatible in the codecs or in the `INVITE` check what codecs you voip provider supports. Maybe disable the video stream. Stop commenting in closed issues.
