### ISSUE TITLE
onlyUseILBC

### ISSUE THREAD

**Issue by kadze** [VoIPGRID/VialerSIPLib#126]
### Version 

3.1.0

### File / Feature

VSLEndpoint.m

### Expected behaviour

use different codecs

### Actual behaviour

use only ILBC codec

 onlyUseILBC(true)   called when setup endpoint

### Other info

Could you tell the reason why only one codec is used?

**Comment by redmerloen** [comment]
iLBC is the codec that uses the least bandwidth. On our own project we only use iLBC that is why it is the standard for the endpoint So when on a data connection it will lower the data usage. U can set the onlyUseILBC(false) with
```[VialerSIPLib sharedInstance] onlyUseIlbc: NO]``` 
When the endpoint has been set up.

**Comment by kadze** [comment]
Thank you for the fast reply. Please give some documentation about library limitations or additional settings when they appear next time.
