### ISSUE TITLE
errors after update 

### ISSUE THREAD

**Issue by masiiha** [VoIPGRID/VialerSIPLib#132]
@redmerloen 
![screen shot 2018-04-05 at 3 21 32 pm](https://user-images.githubusercontent.com/26216784/38362549-84718ae4-38e6-11e8-8436-ebdf4d6c3552.png)

**Comment by redmerloen** [comment]
Could you try this? 
`rm -rf /Users/$USER/Library/Caches/CocoaPods`

**Comment by masiiha** [comment]
I did this but did not answer right

**Comment by masiiha** [comment]
@redmerloen 
it didn't work 
![screen shot 2018-04-07 at 10 32 08 am](https://user-images.githubusercontent.com/26216784/38451962-12de4f60-3a4f-11e8-96f7-1e6cd68dda97.png)

**Comment by redmerloen** [comment]
could you try install `git-lfs`
and do a `rm /Users/$USER/Library/Caches/CocoaPods`
after that do a `pod deintegrate`
and a `pod install`
