### ISSUE TITLE
Video support

### ISSUE THREAD

**Issue by beraylik** [VoIPGRID/VialerSIPLib#134]
Hi im using the latest for now VialerSIPLib 3.1.3 in my swift project

Does it have support for video calling?
If so, can someone provide me with the code snippets on swift?

In changelogs I noticed that there was added video support since 2.6.0, but I can't find any documentation on that

**Comment by redmerloen** [comment]
Video support has been added, but the Example project does not yet updated with it. Sorry can't help you with it at the moment.

**Comment by beraylik** [comment]
Could you please show me at least few lines on how to make video call and assigning the view for video call?

Thank you

**Comment by Vasilich1984** [comment]
Hi beraylik, you can try following methods:

Add into VSLCall class following methods (and probably into VSLCallManager):
- (void)answerWithVideoWithCompletion:(void (^)(NSError *error))completion {
    
    pjsua_call_setting opt;
    pjsua_call_setting_default(&opt);
   //opt.vid_cnt = 0; //option to disable video in the call
       
    pj_status_t status;
    
    if (self.callId != PJSUA_INVALID_ID) {
        
        //ONEGO: use pjsua_call_answer2 -> doesn't answer call correctly
        status = pjsua_call_answer2((int)self.callId, &opt, PJSIP_SC_OK, NULL, NULL);
        
        if (status != PJ_SUCCESS) {
            DDLogError(@"Could not answer call PJSIP returned status code:%d", status);
            NSError *error = [NSError VSLUnderlyingError:nil
                                 localizedDescriptionKey:NSLocalizedString(@"Could not answer call", nil)
                             localizedFailureReasonError:[NSString stringWithFormat:NSLocalizedString(@"PJSIP status code: %d", nil), status]
                                             errorDomain:VSLCallErrorDomain
                                               errorCode:VSLCallErrorCannotAnswerCall];
            completion(error);
        } else {
            completion(nil);
        }
        
    } else {
        DDLogError(@"Could not answer call, PJSIP indicated callId(%ld) as invalid", (long)self.callId);
        NSError *error = [NSError VSLUnderlyingError:nil
                             localizedDescriptionKey:NSLocalizedString(@"Could not answer call", nil)
                         localizedFailureReasonError:[NSString stringWithFormat:NSLocalizedString(@"Call Id: %d invalid", nil), self.callId]
                                         errorDomain:VSLCallErrorDomain
                                           errorCode:VSLCallErrorCannotAnswerCall];
        completion(error);
    }
}

- (void) displayWindow: (UIView *) parent {
//#if PJSUA_HAS_VIDEO
    
    int vid_idx;
    pjsua_vid_win_id wid;
    
    vid_idx = pjsua_call_get_vid_stream_idx(self.callId);
    if (vid_idx >= 0) {
        pjsua_call_info ci;
        pjsua_call_get_info(self.callId, &ci);
        wid = ci.media[vid_idx].stream.vid.win_in;
      
        pjsua_vid_win_info wi;
        if (pjsua_vid_win_get_info(wid, &wi) == PJ_SUCCESS) {
            UIView *view = (__bridge UIView *)wi.hwnd.info.ios.window;
            
            dispatch_async(dispatch_get_main_queue(), ^{
                [parent addSubview:view];
            });
        }
    }
}

Somewhere when you answer call
- (IBAction) answerButtonActionVidAfter: (id) sender {
   
     [self.call answerWithVideoWithCompletion:^(NSError * _Nullable error) {
        if (error) {
            DDLogError(@"Call answer error: %@", error);
        } else {
            //GUI
            [self.call displayWindow:self.videoViewVidAfter]; //define view on the controller where to show video

       .....
       }
     }];
}

**Comment by redmerloen** [comment]
The VSLCallManager should have all the call answer functions.
In time all the `hangup` / `decline` / `answer` are going to be removed from the VSLCall class.

**Comment by fukemy** [comment]
hi, can i ask a question:  How to know when call is connected? Thanks
