### ISSUE TITLE
blind transfer

### ISSUE THREAD

**Issue by masiiha** [VoIPGRID/VialerSIPLib#135]
@redmerloen 
I need to blind the transfer
Do you support this type?

**Comment by redmerloen** [comment]
It has been built with the idea of using attended transfers.
So building a blind transfer shouldn't be all that difficult

**Comment by masiiha** [comment]
@redmerloen 
Do you have an idea for this?

**Comment by redmerloen** [comment]
@masiiha check PR #137

**Comment by masiiha** [comment]
Thanks a lot
