### ISSUE TITLE
keys.swift   lost

### ISSUE THREAD

**Issue by xingyifeng** [VoIPGRID/VialerSIPLib#136]
### Version

{version or tag here}

### File / Feature

{file or feature containing the issue}

### Expected behavior

{what should happen}

### Actual behavior

{what happens}

### Stacktrace / Error message

{paste here}

### Other info

{anything else that might be related/useful}

**Comment by redmerloen** [comment]
There is `Keys.swift.example` in the `Utils` folder when in XCode.
https://github.com/VoIPGRID/VialerSIPLib/blob/develop/Example/VialerSIPLib/Keys.swift.example
Otherwise there it is.
