### ISSUE TITLE
Installation errors 

### ISSUE THREAD

**Issue by cxiaosi** [VoIPGRID/VialerSIPLib#141]
Hello ！
I'm getting this error, When I was doing the installation.

---------
myMAC:testtt  $ pod install
Analyzing dependencies
Downloading dependencies
Installing CocoaLumberjack (3.4.2)
Installing Reachability (3.2)
Installing Vialer-pjsip-iOS (3.3.6)

[!] Error installing Vialer-pjsip-iOS
[!] /usr/bin/git clone https://github.com/VoIPGRID/Vialer-pjsip-iOS.git /var/folders/5_/zj809cdj2gn_yppq6s4n2jwh0000gn/T/d20180605-2369-1h2vznp --template= --single-branch --depth 1 --branch 3.3.6

Cloning into '/var/folders/5_/zj809cdj2gn_yppq6s4n2jwh0000gn/T/d20180605-2369-1h2vznp'...
Note: checking out '6acb14fe7cc69fe4fab0fead52a2710ca0521c04'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

error: git-lfs smudge 'Pod/VialerPJSIP.a' died of signal 11
error: external filter 'git-lfs smudge %f' failed 139
error: external filter 'git-lfs smudge %f' failed
fatal: Pod/VialerPJSIP.a: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
---------

Any help will be appreciated.

**Comment by redmerloen** [comment]
Can you try cleaning your local Cocoapods cache? by doing `rm -rf /Users/$USER/Library/Caches/CocoaPods` and try again

**Comment by johnryan** [comment]
@redmerloen I'm getting the same issue, `rm -rf /Users/$USER/Library/Caches/CocoaPods` didn't fix it

**Comment by sasan-soroush** [comment]
@redmerloen How did you solve this?
