### ISSUE TITLE
CallKit: Incoming call handling issue

### ISSUE THREAD

**Issue by mital87** [VoIPGRID/VialerSIPLib#143]
@redmerloen:  Suppose, **User B** calls to **User A.** **User A** has picked up the call & He has started to talk with **User B.** Now, **User C** calls to **User A.** Now, **User A** has been seen that there are 3 options: End & Accept, Hold & Accept and Decline. I have pressed Hold & Accept key, the current call has hold & start to talk with the **User C.** Then, I have clicked the app icon from the call kit screen, this was redirected me to the active call screen. Then, I have clicked the hold button again, so the unhold function has started. Now, All the 3 Users have a conference call & they have talked with each other.

So, How can I resolve this issue? Please help me to resolve this weird issue. 

Thanking You.

**Comment by mital87** [comment]
@redmerloen: Can you please help me to fix this issue?

**Comment by redmerloen** [comment]
Multiple call handling is not yet supported by the app. Not sure which direction it will go for now

**Comment by mital87** [comment]
@redmerloen: This is the basic functionality. How long will you take to support this feature?

**Comment by redmerloen** [comment]
This is current not a priority of fixing the issue. As needs further investigation to handle it correctly. As we need to check how the call needs to be handled. As everything has been designed with a single call except for doing a transfer.

**Comment by jeremynorman89** [comment]
We do not have any immediate plans to include this but would happily review a pull request with this functionality added.
