### ISSUE TITLE
Crash on toggleHold

### ISSUE THREAD

**Issue by lexin** [VoIPGRID/VialerSIPLib#147]
1. I am calling VSLCallManager toggleHold. And it works on simulator but crashes on the real device iPhone SE.  
Assertion failed: (!"Shouldn't reach here"), 

2. Is it possible to notify User A with some ringing sound or text message when User B holds the call? 

<img width="1384" alt="2018-06-26 18 46 44" src="https://user-images.githubusercontent.com/367295/41924002-98133f68-7971-11e8-9ba5-f57631f95ae3.png">

**Comment by redmerloen** [comment]
It looks like the code you are using is old. Try updating to the newest version and see if that fixes it.
And for 2. This should be handle by your PBX (for example asterisks starting a waiting music) this isn't going to be implemented by this library

**Comment by lexin** [comment]
Ok. thank you! I'll try to update the lib. And also thanks for the advice about p2.

**Comment by lexin** [comment]
After updating the library it doesn't crash at Hold. Thank you!
