### ISSUE TITLE
Can't run example app

### ISSUE THREAD

**Issue by lexin** [VoIPGRID/VialerSIPLib#148]
Hello. I tried two different versions. Example apps. 
VialerSIPLib-3.1.2 and VialerSIPLib-3.3.0 
1. VialerSIPLib-3.1.2  - when I clean cocoapods cache with a help of 
https://github.com/VoIPGRID/VialerSIPLib/issues/127 it pulls whole size of lib 130 mb but when I try to run example project I get 
<img width="1406" alt="2018-06-30 19 33 14" src="https://user-images.githubusercontent.com/367295/42127170-7a5b9a28-7c9c-11e8-81f3-15cc97998e03.png">

2.  VialerSIPLib-3.3.0 when I clean cocoapods cache it pulls only  lib with 5.6 mb. I seems that it's not correct size?

**Comment by redmerloen** [comment]
Check the readme that is mentioning this issue and has a solution to make it work.
`rm -rf /Users/$USER/Library/Caches/CocoaPods`

**Comment by lexin** [comment]
I did it. And tried the whole process several times. It didn't help for 3.3.0. But  VialerSIPLib-3.1.2 works correctly. 
Can't use latest example.

**Comment by lexin** [comment]
You know, the mandatory step for me was the rebooting Mac OS after cleaning CocoaPod cache folder. Only after that it pulled full size file.
