### ISSUE TITLE
Call Kit - Speaker button issue

### ISSUE THREAD

**Issue by lexin** [VoIPGRID/VialerSIPLib#150]
Hello. User gets the call in the app, starts a conversation and turn on the speaker by setting VSLAudioController output  = VSLAudioControllerOutputSpeaker. After that user goes to lock screen and sees CallKit UI. Speaker button is turned On, audio stream is going through the speaker - on this state it's ok. Then user presses on Speaker button for turning OFF loud mode, but the audio stream is still going through the speaker. After couple of seconds the button again in a switch on state. Next attempts are with the same result. 

It seems that it's an issue with audiosession configuration, but I can't manage it.

**Comment by lexin** [comment]
I looked for the info and find some links 
https://stackoverflow.com/questions/49170274/callkit-loudspeaker-bug-how-whatsapp-fixed-it
https://forums.developer.apple.com/thread/64544#189703
https://stackoverflow.com/questions/48023629/abnormal-behavior-of-speaker-button-on-system-provided-call-screen?rq=1

Could we manage this issue on our side?

**Comment by lexin** [comment]
Does anybody have ideas?

**Comment by jeremynorman89** [comment]
Hey,

Are you still experiencing this issue? We weren't able to replicate it.
