### ISSUE TITLE
Error when call pjsua_init

### ISSUE THREAD

**Issue by invisible66** [VoIPGRID/VialerSIPLib#157]
### Version
v3.4.0

Hi everybody. I got this error when i call `VialerSIPLib.sharedInstance().configureLibrary(withEndPointConfiguration: endpointConfiguration)`. I used this library another Obj-c project. But my swift project not working :( what sould i do? 

**Edit** : I got this error on VialerSIPLib example project too..

     myProject(355,0x10176ab80) malloc: can't allocate region
     *** mach_vm_map(size=4303552512) failed (error code=3)
     myProject(355,0x10176ab80) malloc: *** set a breakpoint in malloc_error_break to debug

**Comment by redmerloen** [comment]
So the project is working in your Obj-c application but not in your swift project?

**Comment by invisible66** [comment]
> So the project is working in your Obj-c application but not in your swift project?

Yes..

**Comment by invisible66** [comment]
I returned v3.3.4. It's working perfectly.. Thanks..

**Comment by ratan93** [comment]
Hello Invisible66,
  Hope you are doing well!!
I am also having the same issue after running example application. I also checkout git commit for v3.3.4 but it is crashing on same location. Do you have any other solution?

Please reply as it is needed urgently. @invisible66 @redmerloen  I shall be obliged.

Thanks,
Ratneshwar

**Comment by invisible66** [comment]
@ratan93 You can try last version (3.5.2). It's perfectly working..
