### ISSUE TITLE
crash in many ways:

### ISSUE THREAD

**Issue by sunyizhangyuan** [VoIPGRID/VialerSIPLib#158]
Hi:
    1 . crashed in acc_check_nat_addr :  Have any ideas?
<img width="482" alt="2018-10-19 14 30 20" src="https://user-images.githubusercontent.com/3146120/47201224-b7b8a580-d3ab-11e8-9ea3-0000c41b3f90.png">

    2 . crashed in pjmedia_conf_add_port : 
<img width="451" alt="2018-10-19 14 33 18" src="https://user-images.githubusercontent.com/3146120/47201310-f77f8d00-d3ab-11e8-88dc-d2791cc344df.png">

    3 . crashed in pj_sockaddr_get_addr : 

<img width="388" alt="2018-10-19 14 34 26" src="https://user-images.githubusercontent.com/3146120/47201433-62c95f00-d3ac-11e8-91f8-ccd5a2b27ba0.png">

Thanks.

**Comment by redmerloen** [comment]
Little more information would be nice, next time i'm closing the issue immediately if the template is not filled it in.

What is what you tried to do?
Start the example project? or running from your own project? 
Try disabling BITCODE if you have it enabled in your project?
