### ISSUE TITLE
How to add 'SQLite' library to project

### ISSUE THREAD

**Issue by hamidVahed** [VoIPGRID/VialerSIPLib#160]
I use this project , and I need to install ‘SQLite.swift’ pod library.
After install pod I can’t add library into project because face to the error like that :

<img width="1436" alt="screen shot 2018-10-22 at 4 56 41 pm" src="https://user-images.githubusercontent.com/44376623/47309280-d4b9d680-d640-11e8-88e2-8e3e82ef8256.png">

**Comment by redmerloen** [comment]
![image](https://user-images.githubusercontent.com/12196822/47993780-afbd6d00-e0f0-11e8-9898-2dd78ba7cef1.png)
Isn't it an issue with SQLite?
