### ISSUE TITLE
How did you do that? :)

### ISSUE THREAD

**Issue by invisible66** [VoIPGRID/VialerSIPLib#161]
When i want to add new file to your example project, It's automatically add "VSL" to file name :) 

Can you explain how did you do this please :)

![ekran resmi 2018-10-25 16 44 09](https://user-images.githubusercontent.com/8086679/47504725-7f1a3f80-d875-11e8-8211-7568c7f647c6.png)

**Comment by redmerloen** [comment]
Here you go :)
![image](https://user-images.githubusercontent.com/12196822/47772726-eefe4f00-dce7-11e8-9b63-4c5ddc643780.png)

**Comment by invisible66** [comment]
Thanks so much :)
