### ISSUE TITLE
pjsua_acc_set_registration always returns PJ_SUCCESS

### ISSUE THREAD

**Issue by invisible66** [VoIPGRID/VialerSIPLib#162]
### Version

3.3.4 ( same in 3.4.0 )

### File / Feature

VSLAccount.m

### Expected behavior

if username or password invalid, it must return false (i think)

### Actual behavior

it returns success when username or password was wrong..

### Other info

if registration address isn't valid it's returning error code.

**Comment by redmerloen** [comment]
Good point! I will see if this is possible to add

**Comment by invisible66** [comment]
I think, if account registration failed, it should be removed from `VSLEndPoint.accounts`. Is't it ? So we can change account name, password or domain and re-send register. Am i wrong?

**Comment by redmerloen** [comment]
@invisible66 I've created a PR that would fix this issue in the next release. When there is a "403" error code during the registration it will return a failed through the completion block.

**Comment by invisible66** [comment]
I tried PR codes but it didn't call `registrationCompletionBlock`. I add else statement to `if (self.shouldReregister) {` and called `registrationCompletionBlock`. is it wrong?


     if (code == 0 || (code != PJSIP_SC_FORBIDDEN && accountInfo.expires == -1)) {
        self.accountState = VSLAccountStateDisconnected;
        if (self.shouldReregister) {
            [self registerAccountWithCompletion:^(BOOL success, NSError * _Nullable error) {
                if (success) {
                    VSLLogInfo(@"Account was re-registerd after a sucessfull unregister.");
                    self.shouldReregister = NO;
                    [self reinviteActiveCalls];
                } else {
                    VSLLogWarning(@"Unable to re-register account");
                    self.shouldReregister = NO;
                }
            }];
        } else {
            if (self.registrationCompletionBlock) {
                VSLLogVerbose(@"Account not registered");
                self.registrationCompletionBlock(NO, nil);
                self.registrationCompletionBlock = nil;
            }
        }
        self.registrationInProgress = NO;
    }

**Comment by redmerloen** [comment]
Can you check your sip messages? Or print the output of `code`?

**Comment by invisible66** [comment]
`code` returns PJSIP_SC_UNAUTHORIZED.

![ekran resmi 2018-11-07 16 02 54](https://user-images.githubusercontent.com/8086679/48133081-af66d280-e2a6-11e8-9437-84cf7d77ff44.png)

**Comment by redmerloen** [comment]
Thanks, i will expand the check for me w wrong password returned a forbidden

**Comment by redmerloen** [comment]
Cool, i will create a new version of the Library soon. So this can be added in the next release

**Comment by redmerloen** [comment]
The release is made to 3.4.1 so if you update the library it should be there!

**Comment by invisible66** [comment]
Perfect. Thanks :)

**Comment by invisible66** [comment]
Hey, There is a new error i guess :(

If password is wrong it's working but if i re-send wrong password, i got `Assertion Failed` in `pjsua_acc_get_info`


     - (NSInteger)registrationStatus {
         if (self.accountId == PJSUA_INVALID_ID) {
             return 0;
         }
         pjsua_acc_info accountInfo;
         pj_status_t status;

         status = pjsua_acc_get_info((pjsua_acc_id)self.accountId, &accountInfo);
         if (status != PJ_SUCCESS) {
             return 0;
         }
         return accountInfo.status;
     }

**Comment by redmerloen** [comment]
Yes i have seen it, i will see what is happening soon

**Comment by redmerloen** [comment]
@invisible66 Are you using the methods in the VialerSIPLib.h to register an account?

**Comment by invisible66** [comment]
> @invisible66 Are you using the methods in the VialerSIPLib.h to register an account?

i guess.. I tried your example project..

**Comment by redmerloen** [comment]
This is ` if (self.accountId == PJSUA_INVALID_ID) {`  should catch that assertion error.

**Comment by invisible66** [comment]
`PJSUA_INVALID_ID ` is `-1` but `self.accountId = 0`. So i think it can not catch 

![ezgif-1-4791b67b2875](https://user-images.githubusercontent.com/8086679/48779511-cbc42f80-ece8-11e8-95ef-18fa0aeeadb8.gif)

**Comment by invisible66** [comment]
I got same error in another project (Obj-C). if notification comes when app at background and account is not register it's crashing same line. 

`Assertion failed: (!"Calling pjlib from unknown/external thread. You must " "register external threads with pj_thread_register() " "before calling any pjlib functions."), function pj_thread_this, file ../src/pj/os_core_unix.c, line 692.
`

**Comment by invisible66** [comment]
I got same error in another project (Obj-C). if notification comes when app at background and account is not register it's crashing same line.

Assertion failed: (!"Calling pjlib from unknown/external thread. You must " "register external threads with pj_thread_register() " "before calling any pjlib functions."), function pj_thread_this, file ../src/pj/os_core_unix.c, line 692.

**Comment by redmerloen** [comment]
Can you test this branch `feature/invalid-accounts` see if that is fixing anything?

**Comment by invisible66** [comment]
Hey dude congratulations :) It's perfectly working..
