### ISSUE TITLE
Configure Library for own SIP Server 

### ISSUE THREAD

**Issue by sandeep2244** [VoIPGRID/VialerSIPLib#166]
Hello,

Where i want to add my own SIP account details, to work with own SIP server 

I just to configure with own SIP server in IOS app 

Thank you

**Comment by invisible66** [comment]
In example project you have to add your account details in `Keys.swift` 

Account details must be in `SipUser.swift`.

You have to read [Getting Started Guide](https://github.com/VoIPGRID/VialerSIPLib/blob/develop/Documentation/GettingStarted.md)

**Comment by sandeep2244** [comment]
@invisible66 

can you help me for below solution 

how to use libre as SIP gateway in IOS ?

```

I have my own SIP server(Astrisk) credential wich i need to just configure in gateway and call to PSTN number

 Webrtc -> SIP gateway -> Server(Asterisk) -> PSTN
```
So for which SIP gateway i need to use 

Thank you

**Comment by jeremynorman89** [comment]
This isn't something we have ever implemented in this library as it's not a feature we can make use of, if you wish to add it via pull-request we will happily review it.
