### ISSUE TITLE
VialerSIPLib_Example[8534:1564957] [avas] AVAudioSessionPortImpl.mm:56:ValidateRequiredFields: Unknown selected data source for Port Receiver (type: Receiver)

### ISSUE THREAD

**Issue by azhari** [VoIPGRID/VialerSIPLib#168]
### Version

3.4.2

### File / Feature

Audio input/output when making call

### Expected behavior

Should be able to use mic and speaker 

### Stacktrace / Error message

VialerSIPLib_Example[8534:1564957] [avas] AVAudioSessionPortImpl.mm:56:ValidateRequiredFields: Unknown selected data source for Port Receiver (type: Receiver)

VialerSIPLib_Example[8534:1564957] [avas] AVAudioSessionPortImpl.mm:56:ValidateRequiredFields: Unknown selected data source for Port Speaker (type: Speaker)

### Other info

- Tested using physical iPhone6(iOS 12.1) 
- ejabberd 17.07 as SIP server

**Comment by jeremynorman89** [comment]
We concluded that this was a bug on Apple's side (https://forums.developer.apple.com/thread/108785) with no clear fix.
