### ISSUE TITLE
WEBRTC calling to Only PSTN for ios app in swift 

### ISSUE THREAD

**Issue by sandeep2244** [VoIPGRID/VialerSIPLib#169]
hello,

i am developing app for ios in swift(Webrtc),
i would like to know About how i can use pjsip library for that,
WEBRTC -> PJSIP(SIP) -> PSTN (In IOS)
How can i do this,any one know about any link or cocopods for that

Thank you

**Comment by jeremynorman89** [comment]
Hi,

Issues raised here are meant to be directly related to VialerSIPLib and this library would not make any sense to use in the scenario you are describing, therefore I am going to close it.
