### ISSUE TITLE
Audio cut-out problem after 3.3.0

### ISSUE THREAD

**Issue by invisible66** [VoIPGRID/VialerSIPLib#170]
I think, After 3.3.0, this library has audio cut-out issue.. when we make call, it's sending re-invite every 2 second.. Media is update so Call mute not working (#165) I will use 3.2.0. I hope this problem will be solved in next versions.. Thanks..

3.2.0 is working perfectly. 

### Version

3.4.2

### Stacktrace / Error message

      💚 DEBUG   13:45:46.079 [VSLEndpoint void logCallBack(int, const char *, int):536] pjsua_media.c  .....Call 0: updating media..
      💚 DEBUG   13:45:46.079 [VSLEndpoint void logCallBack(int, const char *, int):536]          pjsua_media.c  .......Media stream call00:0 is destroyed
      💚 DEBUG   13:45:46.079 [VSLEndpoint void logCallBack(int, const char *, int):536]            pjsua_aud.c  ......Audio channel update..
      💚 DEBUG   13:45:46.080 [VSLEndpoint void logCallBack(int, const char *, int):536]        strm0x10c8ca028  .......Encoder stream started
      💚 DEBUG   13:45:46.080 [VSLEndpoint void logCallBack(int, const char *, int):536]        strm0x10c8ca028  .......Decoder stream started
      💚 DEBUG   13:45:46.080 [VSLEndpoint void logCallBack(int, const char *, int):536]          pjsua_media.c  ......Audio updated, stream #0: PCMA (sendrecv)
      💜 VERBOSE 13:45:46.080 [VSLEndpoint void onCallMediaState(pjsua_call_id):593] Received MediaState update for call:15DC2D8C-F31E-49B2-8372-24A64BCC47A6
      💜 VERBOSE 13:45:46.080 [VSLCall -[VSLCall mediaStateChanged:]:406] Media State Changed from VSLMediaStateActive to VSLMediaStateActive
      💙 INFO    13:45:46.080 [VSLRingback -[VSLRingback stop]:94] Stop ringback, isPlaying: NO
      💚 DEBUG   13:45:46.080 [VSLEndpoint void logCallBack(int, const char *, int):536]            pjsua_aud.c  .....Conf connect: 2 --> 0
      💚 DEBUG   13:45:46.080 [VSLEndpoint void logCallBack(int, const char *, int):536]           conference.c  ......Port 2 (sip:XXXXXXXXXX@sip.******.com) transmitting to port 0 (iPhone IO device)
      💚 DEBUG   13:45:46.081 [VSLEndpoint void logCallBack(int, const char *, int):536]            pjsua_aud.c  .....Conf connect: 0 --> 2
      💚 DEBUG   13:45:46.081 [VSLEndpoint void logCallBack(int, const char *, int):536]           conference.c  ......Port 0 (iPhone IO device) transmitting to port 2 (sip:XXXXXXXXXX@sip.************)
      💚 DEBUG   13:45:46.081 [VSLEndpoint void logCallBack(int, const char *, int):536]           pjsua_core.c  .....TX 626 bytes Request msg ACK/cseq=6343 (tdta0x10caf54a8) to UDP XXX.XXX.XXX.189:5060:
      ACK sip:100035XXXXXXXXXX@XXX.XXX.XXX.202:5060 SIP/2.0
      Via: SIP/2.0/UDP 192.168.0.66:40530;rport;branch=z9hG4bKPj9Yz2x1eyorup87tKbme-QKqr7WWmTuI8
      Max-Forwards: 70
      From: sip:XXXYYYZZZ@sip.***********;tag=yxznlh-8SF2x4TiQif5ULDfmnK4TLWpH
      To: sip:XXXXXXXXXX@sip.************;tag=as26a4f05d
      Call-ID: DTYEq-C16HB4DYMP4br8B83fKQozV9EY
      CSeq: 6343 ACK
      Route: <sip:XXX.XXX.XXX.189;lr;ftag=yxznlh-8SF2x4TiQif5ULDfmnK4TLWpH>
      Route: <sip:XXX.XXX.XXX.102:5061;lr;ftag=yxznlh-8SF2x4TiQif5ULDfmnK4TLWpH;did=07b.eea1;vsf=AAAAAAEFCAYAAAAFBgB2RSlBFltLTF9dWgBSX18udHI-;vst=AAAAAAUBBwEKAQ4GBARxcUtcXhZWS0NJQl0cY29tLnRy>
      Content-Length:  0

      --end msg--
      💚 DEBUG   13:45:46.088 [VSLEndpoint void logCallBack(int, const char *, int):536]           pjsua_call.c  .Call 0 sending re-INVITE for updating media session to use only one codec
      💚 DEBUG   13:45:46.089 [VSLEndpoint void logCallBack(int, const char *, int):536]           pjsua_core.c  ....TX 1223 bytes Request msg INVITE/cseq=6344 (tdta0x10cb684a8) to UDP XXX.XXX.XXX.189:5060:
      INVITE sip:100035XXXXXXXXXX@XXX.XXX.XXX.202:5060 SIP/2.0
      Via: SIP/2.0/UDP 192.168.0.66:40530;rport;branch=z9hG4bKPjfZ9bySWW9x82aF8EkhRABK7sbTQUp6vb 
      Max-Forwards: 70
      From: sip:XXXYYYZZZ@sip.***********;tag=yxznlh-8SF2x4TiQif5ULDfmnK4TLWpH
      To: sip:XXXXXXXXXX@sip.************;tag=as26a4f05d
      Contact: <sip:XXXYYYZZZ@192.168.0.66:40530;ob>
      Call-ID: DTYEq-C16HB4DYMP4br8B83fKQozV9EY
      CSeq: 6344 INVITE
      Route: <sip:XXX.XXX.XXX.189;lr;ftag=yxznlh-8SF2x4TiQif5ULDfmnK4TLWpH>
      Route: <sip:XXX.XXX.XXX.102:5061;lr;ftag=yxznlh-8SF2x4TiQif5ULDfmnK4TLWpH;did=07b.eea1;vsf=AAAAAAEFCAYAAAAFBgB2RSlBFltLTF9dWgBSX18udHI-;vst=AAAAAAUBBwEKAQ4GBARxcUtcXhZWS0NJQl0cY29tLnRy>

      Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
      Supported: replaces, 100rel, timer, norefersub
      Session-Expires: 1800;refresher=uas
      Min-SE: 90
      Content-Type: application/sdp
      Content-Length:   313

      v=0
      o=- 3754377934 3754377940 IN IP4 192.168.2.42
      s=pjmedia
      b=AS:84
      t=0 0
      a=X-nat:0
      m=audio 4004 RTP/AVP 8 96
      c=IN IP4 192.168.2.42
      b=TIAS:64000
      a=rtcp:4005 IN IP4 192.168.2.42
      a=ssrc:1278702608 cname:567fd8ea637a1703
      a=rtpmap:8 PCMA/8000
      a=rtpmap:96 telephone-event/8000
      a=fmtp:96 0-16
      a=sendrecv

      --end msg--
      💚 DEBUG   13:45:46.114 [VSLEndpoint void logCallBack(int, const char *, int):536]           pjsua_core.c  .RX 402 bytes Response msg 100/INVITE/cseq=6344 (rdata0x10ccd5828) from UDP XXX.XXX.XXX.189:5060:
      SIP/2.0 100 trying -- your call is important to us

      Via: SIP/2.0/UDP 192.168.0.66:40530;rport=40530;branch=z9hG4bKPjfZ9bySWW9x82aF8EkhRABK7sbTQUp6vb;received=192.168.0.66
      From: sip:XXXYYYZZZ@sip.***********;tag=yxznlh-8SF2x4TiQif5ULDfmnK4TLWpH
      To: sip:XXXXXXXXXX@sip.************;tag=as26a4f05d
      Call-ID: DTYEq-C16HB4DYMP4br8B83fKQozV9EY
      CSeq: 6344 INVITE
      Server: NetGSM
      Content-Length: 0

      --end msg--
      💚 DEBUG   13:45:46.119 [VSLEndpoint void logCallBack(int, const char *, int):536]           pjsua_core.c  .RX 854 bytes Response msg 200/INVITE/cseq=6344 (rdata0x10ccd5828) from UDP XXX.XXX.XXX.189:5060:
      SIP/2.0 200 OK
      Via: SIP/2.0/UDP 192.168.0.66:40530;received=192.168.0.66;rport=40530;branch=z9hG4bKPjfZ9bySWW9x82aF8EkhRABK7sbTQUp6vb
      From: sip:XXXYYYZZZ@sip.***********;tag=yxznlh-8SF2x4TiQif5ULDfmnK4TLWpH
      To: sip:XXXXXXXXXX@sip.************;tag=as26a4f05d
      Call-ID: DTYEq-C16HB4DYMP4br8B83fKQozV9EY
      CSeq: 6344 INVITE
      Server: sipgw2
      Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
      Supported: replaces, timer
      Session-Expires: 1800;refresher=uas
      Contact: <sip:100035XXXXXXXXXX@XXX.XXX.XXX.202:5060>
      Content-Type: application/sdp
      Require: timer
      Content-Length: 231

      v=0
      o=root 576436610 576436615 IN IP4 XXX.XXX.XXX.202
      s=Asterisk PBX 11.25.3
      c=IN IP4 XXX.XXX.XXX.202
      t=0 0
      m=audio 15122 RTP/AVP 8 96
      a=rtpmap:8 PCMA/8000
      a=rtpmap:96 telephone-event/8000
      a=fmtp:96 0-16
      a=ptime:20
      a=sendrecv

**Comment by jeremynorman89** [comment]
I'm closing this as it's referring to the same underlying issues as #165
