### ISSUE TITLE
Error: framework is not compiled for arm64

### ISSUE THREAD

**Issue by mital87** [VoIPGRID/VialerSIPLib#173]
### Version

Pod 3.5.1

### Information

I have updated my **VialerSIPLib** pod **3.3.1 to 3.5.1**. When I have built my project that time I have faced **" symbol(s) not found for architecture arm64"** error. After that, I have downloaded the example code & try to build example code as well but I have got the same error message in the example code. So can you fix these issues on an urgent basis?

I think so the framework is not compiled for arm64. Can you please make sure with your end.

### Stacktrace / Error message

****ld: warning: ignoring file /Pods/Vialer-pjsip-iOS/VialerPJSIP.framework/VialerPJSIP, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): /Pods/Vialer-pjsip-iOS/VialerPJSIP.framework/VialerPJSIP****

> Undefined symbols for architecture arm64:
>   "_pjsua_acc_get_config", referenced from:
>       -[VSLAccount registerAccountWithCompletion:] in libVialerSIPLib.a(VSLAccount.o)
>   "_pjsua_acc_del", referenced from:
>       -[VSLAccount removeAccount] in libVialerSIPLib.a(VSLAccount.o)
>   "_pjsua_acc_config_default", referenced from:
>       -[VSLAccount configureWithAccountConfiguration:error:] in libVialerSIPLib.a(VSLAccount.o)
>   "_pjsua_acc_get_info", referenced from:
>       -[VSLAccount registrationStatus] in libVialerSIPLib.a(VSLAccount.o)
>       -[VSLAccount registrationExpiresTime] in libVialerSIPLib.a(VSLAccount.o)
>       -[VSLAccount registerAccountWithCompletion:] in libVialerSIPLib.a(VSLAccount.o)
>       -[VSLAccount accountStateChanged] in libVialerSIPLib.a(VSLAccount.o)
>   "_pjsua_conf_remove_port", referenced from:
>       -[VSLRingback dealloc] in libVialerSIPLib.a(VSLRingback.o)
>       -[VSLRingback stop] in libVialerSIPLib.a(VSLRingback.o)
>   "_pjmedia_tonegen_create2", referenced from:
>       -[VSLRingback init] in libVialerSIPLib.a(VSLRingback.o)
>   "_pjmedia_tonegen_play", referenced from:
>       -[VSLRingback init] in libVialerSIPLib.a(VSLRingback.o)
>   "_pjsua_ip_change_param_default", referenced from:
>       -[VSLEndpoint ipAddressChanged:] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_handle_ip_change", referenced from:
>       -[VSLEndpoint ipAddressChanged:] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_enum_transports", referenced from:
>       -[VSLEndpoint callDealloc:] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_vid_enum_codecs", referenced from:
>       -[VSLEndpoint updateVideoCodecs] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_vid_codec_set_priority", referenced from:
>       -[VSLEndpoint updateVideoCodecs] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_vid_codec_set_param", referenced from:
>       -[VSLEndpoint updateVideoCodecs] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjmedia_endpt_get_codec_mgr", referenced from:
>       -[VSLEndpoint getPjMediaCodecManager] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_acc_is_valid", referenced from:
>       -[VSLAccount isAccountValid] in libVialerSIPLib.a(VSLAccount.o)
>   "_pjmedia_codec_opus_get_config", referenced from:
>       -[VSLEndpoint updateOpusSettings:] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjmedia_codec_mgr_find_codecs_by_id", referenced from:
>       -[VSLEndpoint updateOpusSettings:] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_enum_codecs", referenced from:
>       -[VSLEndpoint updateAudioCodecs] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_codec_set_priority", referenced from:
>       -[VSLEndpoint updateAudioCodecs] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_acc_add", referenced from:
>       -[VSLAccount configureWithAccountConfiguration:error:] in libVialerSIPLib.a(VSLAccount.o)
>   "_pjsua_destroy", referenced from:
>       -[VSLEndpoint destroyPJSUAInstance] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_call_get_info", referenced from:
>       -[VSLCall initInboundCallWithCallId:account:] in libVialerSIPLib.a(VSLCall.o)
>       -[VSLCall connectDuration] in libVialerSIPLib.a(VSLCall.o)
>       -[VSLCall checkIfAudioPresent] in libVialerSIPLib.a(VSLCall.o)
>       -[VSLCall toggleMute:] in libVialerSIPLib.a(VSLCall.o)
>       -[VSLCall calculateStats] in libVialerSIPLib.a(VSLCall.o)
>       -[VSLCallStats generate] in libVialerSIPLib.a(VSLCallStats.o)
>       _onCallMediaState in libVialerSIPLib.a(VSLEndpoint.o)
>       ...
>   "_pjsua_create", referenced from:
>       -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_transport_get_info", referenced from:
>       -[VSLEndpoint callDealloc:] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_logging_config_default", referenced from:
>       -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_config_default", referenced from:
>       -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_vid_codec_get_param", referenced from:
>       -[VSLEndpoint updateVideoCodecs] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_transport_create", referenced from:
>       -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjmedia_port_destroy", referenced from:
>       -[VSLRingback dealloc] in libVialerSIPLib.a(VSLRingback.o)
>   "_pjsua_set_no_snd_dev", referenced from:
>       -[VSLAudioController activateSoundDevice] in libVialerSIPLib.a(VSLAudioController.o)
>       -[VSLAudioController deactivateSoundDevice] in libVialerSIPLib.a(VSLAudioController.o)
>       -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_media_config_default", referenced from:
>       -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_start", referenced from:
>       -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_call_set_hold", referenced from:
>       -[VSLCall toggleHold:] in libVialerSIPLib.a(VSLCall.o)
>   "_pj_thread_is_registered", referenced from:
>       -[VSLAudioController checkCurrentThreadIsRegisteredWithPJSUA] in libVialerSIPLib.a(VSLAudioController.o)
>       -[VSLEndpoint createPJSIPThreadWithError:] in libVialerSIPLib.a(VSLEndpoint.o)
>       -[VSLEndpoint destroyPJSUAInstance] in libVialerSIPLib.a(VSLEndpoint.o)
>       -[VSLRingback checkCurrentThreadIsRegisteredWithPJSUA] in libVialerSIPLib.a(VSLRingback.o)
>   "_pjsua_init", referenced from:
>       -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_call_send_request", referenced from:
>       -[VSLCall sendDTMF:error:] in libVialerSIPLib.a(VSLCall.o)
>   "_pjsua_conf_add_port", referenced from:
>       -[VSLRingback init] in libVialerSIPLib.a(VSLRingback.o)
>   "_pj_thread_register", referenced from:
>       -[VSLAudioController checkCurrentThreadIsRegisteredWithPJSUA] in libVialerSIPLib.a(VSLAudioController.o)
>       -[VSLEndpoint createPJSIPThreadWithError:] in libVialerSIPLib.a(VSLEndpoint.o)
>       -[VSLEndpoint destroyPJSUAInstance] in libVialerSIPLib.a(VSLEndpoint.o)
>       -[VSLRingback checkCurrentThreadIsRegisteredWithPJSUA] in libVialerSIPLib.a(VSLRingback.o)
>   "_pjsua_acc_set_registration", referenced from:
>       -[VSLAccount registerAccountWithCompletion:] in libVialerSIPLib.a(VSLAccount.o)
>       -[VSLAccount unregisterAccount:] in libVialerSIPLib.a(VSLAccount.o)
>   "_pjmedia_codec_opus_set_default_param", referenced from:
>       -[VSLEndpoint updateOpusSettings:] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_call_answer", referenced from:
>       -[VSLCall setCallState:] in libVialerSIPLib.a(VSLCall.o)
>       -[VSLCall decline:] in libVialerSIPLib.a(VSLCall.o)
>   "_pjsua_conf_disconnect", referenced from:
>       -[VSLCall toggleMute:] in libVialerSIPLib.a(VSLCall.o)
>       -[VSLRingback stop] in libVialerSIPLib.a(VSLRingback.o)
>   "_pj_str", referenced from:
>       -[VSLCall sendDTMF:error:] in libVialerSIPLib.a(VSLCall.o)
>       -[VSLRingback init] in libVialerSIPLib.a(VSLRingback.o)
>       -[NSString(PJString) pjString] in libVialerSIPLib.a(NSString+PJString.o)
>   "_pjsua_call_reinvite2", referenced from:
>       -[VSLCall reinvite] in libVialerSIPLib.a(VSLCall.o)
>       -[VSLCall toggleHold:] in libVialerSIPLib.a(VSLCall.o)
>   "_pjsua_call_dial_dtmf", referenced from:
>       -[VSLCall sendDTMF:error:] in libVialerSIPLib.a(VSLCall.o)
>   "_pjsua_set_snd_dev", referenced from:
>       -[VSLAudioController activateSoundDevice] in libVialerSIPLib.a(VSLAudioController.o)
>   "_pjsua_msg_data_init", referenced from:
>       -[VSLCall sendDTMF:error:] in libVialerSIPLib.a(VSLCall.o)
>   "_pjsua_call_hangup", referenced from:
>       -[VSLCall hangup:] in libVialerSIPLib.a(VSLCall.o)
>   "_pj_pool_release", referenced from:
>       -[VSLEndpoint destroyPJSUAInstance] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_pool_create", referenced from:
>       -[VSLEndpoint createPoolForPJSIP] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_call_answer2", referenced from:
>       -[VSLCall answerWithCompletion:] in libVialerSIPLib.a(VSLCall.o)
>   "_pjsua_call_update2", referenced from:
>       -[VSLCall update] in libVialerSIPLib.a(VSLCall.o)
>   "_pjsua_call_xfer_replaces", referenced from:
>       -[VSLCall transferToCall:] in libVialerSIPLib.a(VSLCall.o)
>   "_pjsua_call_get_stream_info", referenced from:
>       -[VSLCallStats generate] in libVialerSIPLib.a(VSLCallStats.o)
>   "_pjmedia_codec_mgr_get_default_param", referenced from:
>       -[VSLEndpoint updateOpusSettings:] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_call_get_stream_stat", referenced from:
>       -[VSLCall checkIfAudioPresent] in libVialerSIPLib.a(VSLCall.o)
>       -[VSLCallStats generate] in libVialerSIPLib.a(VSLCallStats.o)
>   "_pjsua_transport_config_default", referenced from:
>       -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_conf_connect", referenced from:
>       -[VSLCall mediaStateChanged:] in libVialerSIPLib.a(VSLCall.o)
>       -[VSLCall toggleMute:] in libVialerSIPLib.a(VSLCall.o)
>       -[VSLRingback start] in libVialerSIPLib.a(VSLRingback.o)
>   "_pjsua_call_xfer", referenced from:
>       -[VSLCall blindTransferCallWithNumber:] in libVialerSIPLib.a(VSLCall.o)
>   "_pjsua_get_pjmedia_endpt", referenced from:
>       -[VSLEndpoint getPjMediaCodecManager] in libVialerSIPLib.a(VSLEndpoint.o)
>   "_pjsua_call_setting_default", referenced from:
>       -[VSLCall startWithCompletion:] in libVialerSIPLib.a(VSLCall.o)
>       -[VSLCall reinvite] in libVialerSIPLib.a(VSLCall.o)
>       -[VSLCall update] in libVialerSIPLib.a(VSLCall.o)
>       -[VSLCall answerWithCompletion:] in libVialerSIPLib.a(VSLCall.o)
>       -[VSLCall toggleHold:] in libVialerSIPLib.a(VSLCall.o)
>   "_pjsua_call_make_call", referenced from:
>       -[VSLCall startWithCompletion:] in libVialerSIPLib.a(VSLCall.o)

****ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)****

**Comment by Taopath** [comment]
I seem to be having exactly the same problem:
**ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)**

**Comment by azhari** [comment]
Please do refer #127

**Comment by mital87** [comment]
@azhari : I have already referred #127 issue. But didn't solve my problem. That's why I have raised the issue. If you have any idea about it the let me know so I will try that as well.

**Comment by mital87** [comment]
@redmerloen, @jeremynorman89  Can you fix this issues from the latest **pod v3.5.1** in urgent basis? Many users are facing this issue.

**Comment by azhari** [comment]
> @azhari : I have already referred #127 issue. But didn't solve my problem. That's why I have raised the issue. If you have any idea about it the let me know so I will try that as well.

@mital87 Did you try this solution by any chance [https://github.com/VoIPGRID/Vialer-pjsip-iOS/issues/27#issuecomment-405166958](url)

**Comment by jeremynorman89** [comment]
> @redmerloen, @jeremynorman89 Can you fix this issues from the latest **pod v3.5.1** in urgent basis? Many users are facing this issue.

So you definitely have [Git LFS](https://git-lfs.github.com/) installed? This has always been the solution to this problem in the past.

**Comment by mital87** [comment]
Thanks, @azhari & @jeremynorman89  for your valuable suggestion.
