### ISSUE TITLE
Unable to reINVITE call when call is ringing

### ISSUE THREAD

**Issue by arielph** [VoIPGRID/VialerSIPLib#174]
Hi, have you fixed this issue?
http://lists.pjsip.org/pipermail/pjsip_lists.pjsip.org/2017-January/040182.html

I'm using https://github.com/chebur/pjsip and I'm facing this issue when switching 4G->WiFi or 4G->none->4G only for incoming calls. Maybe I will be able to switch to your library.

Sorry for that this issue is not related strictly to an issue with your software.

Kind regards,
Ariel Bogdziewicz

**Comment by jeremynorman89** [comment]
Unfortunately not, reINVITE only works when the call has been established, not during ringing.
