### ISSUE TITLE
Crash On ssertion failed: (contact_rewrite_method == PJSUA_CONTACT_REWRITE_UNREGISTER || contact_rewrite_method == PJSUA_CONTACT_REWRITE_NO_UNREG || contact_rewrite_method == PJSUA_CONTACT_REWRITE_ALWAYS_UPDATE)

### ISSUE THREAD

**Issue by KitFoong94** [VoIPGRID/VialerSIPLib#177]
### Version

Vialer-pjsip-iOS (3.4.1)
VialerSIPLib (3.5.1)

### File / Feature

Re-register account after unregister account

### Expected behavior

Account should be can re-register after unregister account.

### Actual behavior

It can be work on the first time, register and unregister an account.

### Stacktrace / Error message

Assertion failed: (contact_rewrite_method == PJSUA_CONTACT_REWRITE_UNREGISTER || contact_rewrite_method == PJSUA_CONTACT_REWRITE_NO_UNREG || contact_rewrite_method == PJSUA_CONTACT_REWRITE_ALWAYS_UPDATE), function acc_check_nat_addr, file ../src/pjsua-lib/pjsua_acc.c, line 1787.

### Other info

- Swift Project
- the framework with CocoaPods
- Deployment target: iOS 12
- Tested in debug mode on simulator iPhone XS Max with iOS version 12.1

My app first screen was login screen, after login it will setup and register sip account simultaneously. When I logout, it will unregister my account and when I try to login again, it will have register issue. Login interface was not related to SIP account.

Steps to reproduce (in the example app):
- Launch the app
- Login to apps (if success, automatically setup and register sip account)
- Logout (unregister account)
- Login again (if success, automatically setup and register sip account)
- issues happen

**Comment by jeremynorman89** [comment]
> Steps to reproduce (in the example app):

You said this was in the example app, but these steps don't sound like it's coming from the example. Using the example app I'm able to register/deregister as many times as I like without any issue.

Are you able to reproduce the issue in the example app? If not, then maybe have a look at the differences when registering between that and your code.

**Comment by KitFoong94** [comment]
Hi Jeremy, 
  
 Thank for the reply on my issue. I had solved my problem with changing VSLAccountConfiguration (self.contactRewriteMethod = VSLContactRewriteMethodUnregister;), by default it was VSLContactRewriteMethodAlwaysUpdate. I not sure is it was the main issue.
  
 By the way, I had another issue which was incoming call would like to ask you. When I received and accepted incoming call, I pressed on hang up button, it was showing error (Failed to send end session message)
  

�� DEBUG   18:10:35.637 [VSLCall -[VSLCall setCallState:]:128] Call(686D16B4-1200-4FD1-BFE6-52333A45F58D). CallState will change from VSLCallStateNull(0) to VSLCallStateIncoming(2)  

   

�� DEBUG   18:10:38.426 [VSLCall -[VSLCall setCallState:]:128] Call(686D16B4-1200-4FD1-BFE6-52333A45F58D). CallState will change from VSLCallStateIncoming(2) to VSLCallStateEarly(3)  

   

�� DEBUG   18:10:38.428 [VSLCall -[VSLCall setCallState:]:128] Call(686D16B4-1200-4FD1-BFE6-52333A45F58D). CallState will change from VSLCallStateEarly(3) to VSLCallStateConnecting(4)  

   

�� DEBUG   18:10:39.082 [VSLCall -[VSLCall setCallState:]:128] Call(686D16B4-1200-4FD1-BFE6-52333A45F58D). CallState will change from VSLCallStateConnecting(4) to VSLCallStateConfirmed(5)  

   

�� DEBUG   18:10:41.196 [VSLCall -[VSLCall setCallState:]:128] Call(686D16B4-1200-4FD1-BFE6-52333A45F58D). CallState will change from VSLCallStateConfirmed(5) to VSLCallStateDisconnected(6)  

  

❗ ERROR   18:10:41.205 [VSLEndpoint void logCallBack(int, const char *, int):527]           pjsua_call.c  .Failed to send end session message: Unsupported transport (PJSIP_EUNSUPTRANSPORT) [status=171060]  

   

�� INFO    18:10:41.208 [CallKitProviderDelegate -[CallKitProviderDelegate provider:performEndCallAction:]:154] Error hanging up call(686D16B4-1200-4FD1-BFE6-52333A45F58D) error:Error Domain=VialerSIPLib.VSLCall Code=3 "Could not hangup call" UserInfo={NSLocalizedDescription=Could not hangup call, NSLocalizedFailureReason=PJSIP status code: 171060}  

   

   

The connection seen like doesn't had any issues. It can detected connection was disconnected but it can't sent end message to callee device. Hope can get any advice from you.  

   

Thanks and Regards,   

Kit Foong 
  
  
  

----------------------------------------

**Comment by jeremynorman89** [comment]
I'm glad the original problem was fixed, I see you have raised another issue for this problem so I'll close this one.

**Comment by mrfarukturgut** [comment]
@KitFoong94 @jeremynorman89  Hi, I am having same issue in my application. And your solution did not help me. The problem occurs when registration is being tried to be estabilished through a wi-fi network. It is just working fine with cellular network. Tried to set `ContactRewriteMethod` however it did not work.

**Comment by nfinfu** [comment]
@mrfarukturgut did you find a solution?

**Comment by mrfarukturgut** [comment]
@nfinfu I think I found a solution. Sadly though I cant remember the solution and I dont have access to the code. 

I guess installing an early version of the code fixed it but I may be wrong about that also.

**Comment by JawadZebNow** [comment]
I've faced same issue on Android 11, Solved it by adding accountNatConfig.setContactRewriteUse(0). Sharing my Account Config Settings.
