### ISSUE TITLE
Build failr

### ISSUE THREAD

**Issue by zziazm** [VoIPGRID/VialerSIPLib#18]
i have renamed Keys.sample.swift to  Keys.swift, then i built failure:
`
 @IBOutlet weak var numberToDialLabel: UILabel! {
        didSet {
            numberToDialLabel.text = "\(Keys.NumberToCall)"
        }
    }
`
use of unresolved identifier 'Keys'

**Comment by bobvoorneveld** [comment]
Did you add it to the target?

**Comment by bobvoorneveld** [comment]
no reaction, closing issue
