### ISSUE TITLE
G729 codec

### ISSUE THREAD

**Issue by kesslermichael** [VoIPGRID/VialerSIPLib#181]
### Version
3.5.2

### File / Feature
VSLAudioCodecs

### Expected behavior
I'd expect to have G729 codec among all the codecs in `VSLAudioCodec` enum

### Actual behavior
G729 codec is missing 

### Other info
Vialer-pjsip-iOS project (v3.4.1) supports this codec...

**Comment by jeremynorman89** [comment]
I don't see any reason why this shouldn't work, I'll do some testing and will look to create a PR by the end of the week if all is okay.

**Comment by jeremynorman89** [comment]
Hey,

Unfortunately G729 is not supported by Vialer-pjsip-iOS even though I do see it enabled in some of the configuration files, it is not offering it as a valid codec.

As can be seen [in the VoiSmart pjsip builder](https://github.com/VoiSmart/pjsip-android-builder/tree/master/patches/support_g729) there are some hoops to jump through to get it to work, as well as licensing issues.

As we have no use for this codec and it's not just a matter of adding a couple of lines we won't be adding support for G729.
