### ISSUE TITLE
Transitive dependencies issue Pod [URGENT]

### ISSUE THREAD

**Issue by mudassirzulfiqar** [VoIPGRID/VialerSIPLib#195]
### Version

Vialer-pjsip-iOS (3.4.1)
VialerSIPLib (3.5.6)

### File / Feature

pod file
### Expected behavior
Should be able to add into pod file

### Actual behavior
Unable to Add Vialer library 
### Stacktrace / Error message

gnoring iStats-1.6.1 because its extensions are not built.  Try: gem pristine iStats --version 1.6.1
Analyzing dependencies
Downloading dependencies
Using Alamofire (4.8.2)
Installing CocoaLumberjack (3.5.3)
Using DropDown (2.3.13)
Using Firebase (6.7.0)
Using FirebaseAnalytics (6.1.1)
Using FirebaseAnalyticsInterop (1.4.0)
Using FirebaseCore (6.2.1)
Using FirebaseCoreDiagnostics (1.0.1)
Using FirebaseCoreDiagnosticsInterop (1.0.0)
Using FirebaseInstanceID (4.2.3)
Using FirebaseMessaging (4.1.3)
Using GoogleAppMeasurement (6.1.1)
Using GoogleDataTransport (1.1.2)
Using GoogleDataTransportCCTSupport (1.0.2)
Using GoogleUtilities (6.2.5)
Using NSString-Hashes (1.2.2)
Using Protobuf (3.9.0)
Installing Reachability (3.2)
Using ReachabilitySwift (4.3.1)
Using Realm (3.17.3)
Using RealmSwift (3.17.3)
Using SVProgressHUD (2.2.5)
Using SwiftQueue (2.3.0)
Using SwiftyJSON (4.2.0)
Installing Vialer-pjsip-iOS (3.4.1)
Installing VialerSIPLib (3.5.6)
Using nanopb (0.3.901)
[!] The 'Pods-Picasse Receiver' target has transitive dependencies that include static binaries: (/Users/moodi/My files/Picass Receiver IOS/Picasse Receiver/Pods/Vialer-pjsip-iOS/VialerPJSIP.framework)

!] The 'Pods-Picasse Receiver' target has transitive dependencies that include static binaries: (/............./Pods/Vialer-pjsip-iOS/VialerPJSIP.framework)

**Comment by c-Viorel** [comment]
can you show us your pod file?

**Comment by mudassirzulfiqar** [comment]
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
SIPlibVersion = '3.5.6'

target 'EmerGenc' do
use_frameworks!

 pod 'SVProgressHUD'
  pod 'Alamofire', '~> 4.8.1'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'NSString-Hashes', '~> 1.2'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'RealmSwift'
  pod 'SwiftQueue'
  pod 'DropDown'
 pod 'VialerSIPLib', SIPlibVersion // I have to comment this otherwise I have dependency problem and when I open my project I receive weired lexical or preprocessor issue in my previous libraries. To solve this I have to firsr remove  VialerSIPLib library and  reinstall the pod file after removing.


  target 'EmerGenc ReTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

**Comment by c-Viorel** [comment]
You should remove use_framworks! line because vialerSIPLib has as dependency this pod: https://github.com/voipgrid/Vialer-pjsip-iOS, which can't be a dynamic lib. 

Also, you should read the ReadMe file from that link. you will find another solution. (in my case it didn't work)

**Comment by mudassirzulfiqar** [comment]
I have done all the steps which are described in the link you mentioned but it did not work.
I removed **use_frameworks** 
and I added **use_modular_headers!** because of some errors.

Now the pod installation seems working.
After building the project Im getting lots lexical or preprocessor issues from my old library. 
/............../Pods/Vialer-pjsip-iOS/VialerPJSIP.framework/Versions/A/Headers/pj++/list.hpp:23:10: 'pj/list.h' file not found

**Comment by mudassirzulfiqar** [comment]
The issue has been solved the conflicting library was Realm I managed to add Realm using dynamic framework. Now the project compiled successfully

**Comment by eduardothiesen** [comment]
@mudassirzulfiqar how did you solve the conflict with the realm pod? Thanks in advance.
