### ISSUE TITLE
Enhancement: Add support for auth username

### ISSUE THREAD

**Issue by Joker666** [VoIPGRID/VialerSIPLib#2]
Currently it supports username, password, domain and proxy for default account configuration. Maybe also add optional auth username support to default configuration

**Comment by m-vellinga** [comment]
Thanks for the suggestion! When our iOS developers are back they will respond to this enhancement.

**Comment by bobvoorneveld** [comment]
Hi @Joker666, I'll create a ticket and if we find some time, we'll integrate it. Our own implementation has no need for it, so we have to find a way to test if the code actually works. If you find a solution, please create a PR so we can add it to the code.

**Comment by bobvoorneveld** [comment]
Hi @Joker666, we would like to help you further with this issue. Could you explain how you would like to use this? Our PBX uses a combination of account id & domain.
