### ISSUE TITLE
Installing VialerSIPLib using CocoaPods

### ISSUE THREAD

**Issue by mrfarukturgut** [VoIPGRID/VialerSIPLib#203]
### Version

3.6.0

### File / Feature

Installing the library using cocoapods

### Expected behavior

I have put the lines to `podfile` as follows;

```
platform :ios, 13.0

target ...... do 
  pod 'VialerSIPLib'
  #use_frameworks!
end 
```
and pod installs the library with 3 more libraries. Throws no error and prints 
`
Pod installation complete! There is 1 dependency from the Podfile and 4 total pods installed.
`
### Actual behavior

However, when I try to create a account in `AppDelegate` with line of code `var account:VSLAccount!` it throws  `Use of undeclared type VSLAccount`. A Relative error when I try to import the library. I am just trying to reach all methods and classes from my project.

### Other info
Example project works well. I was able to make call. I am using MacOS Catalina and iOS version 13.0 and creating the project with `SwiftUI`

**Comment by mudassirzulfiqar** [comment]
Are you able to receive a call in this version of library?

**Comment by mrfarukturgut** [comment]
Yes I was, when using the example project. However found the solution, it seems xcode requires some cleaning, restarting mac to be able to build the pod.

**Comment by mudassirzulfiqar** [comment]
Cool. I tried a lot Im not Able to receive a call for some reason
