### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by ludivinefafournoux** [VoIPGRID/VialerSIPLib#208]
### Version

3.6.0

### Expected behavior

build successfully example project

### Actual behavior
I download the ZIP, to build and run the example project. I did `pod install`.
I can't run the example project because of arm64 issue.
I tried to clean Cocoapods cache, but no changes.
I've installed git lfs.
I check all issues with reference to arm64 error and I tried all propositions.

### Stacktrace / Error message

`ld: warning: ignoring file /Users/.../Example/Pods/Vialer-pjsip-iOS/VialerPJSIP.framework/VialerPJSIP, building for iOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )
Undefined symbols for architecture arm64:
  "_pjsua_acc_get_config", referenced from:
      -[VSLAccount registerAccountWithCompletion:] in libVialerSIPLib.a(VSLAccount.o)
  "_pjsua_acc_del", referenced from:
      -[VSLAccount removeAccount] in libVialerSIPLib.a(VSLAccount.o)
  "_pjsua_acc_config_default", referenced from:
      -[VSLAccount configureWithAccountConfiguration:error:] in libVialerSIPLib.a(VSLAccount.o)
  "_pjsua_acc_get_info", referenced from:
      -[VSLAccount registrationStatus] in libVialerSIPLib.a(VSLAccount.o)
      -[VSLAccount registrationExpiresTime] in libVialerSIPLib.a(VSLAccount.o)
      -[VSLAccount registerAccountWithCompletion:] in libVialerSIPLib.a(VSLAccount.o)
      -[VSLAccount accountStateChanged] in libVialerSIPLib.a(VSLAccount.o)
  "_pjsua_conf_remove_port", referenced from:
      -[VSLRingback dealloc] in libVialerSIPLib.a(VSLRingback.o)
      -[VSLRingback stop] in libVialerSIPLib.a(VSLRingback.o)
  "_pjmedia_tonegen_create2", referenced from:
      -[VSLRingback init] in libVialerSIPLib.a(VSLRingback.o)
  "_pjmedia_tonegen_play", referenced from:
      -[VSLRingback init] in libVialerSIPLib.a(VSLRingback.o)
  "_pjsua_ip_change_param_default", referenced from:
      -[VSLEndpoint ipAddressChanged:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_handle_ip_change", referenced from:
      -[VSLEndpoint ipAddressChanged:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_enum_transports", referenced from:
      -[VSLEndpoint callDealloc:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_vid_enum_codecs", referenced from:
      -[VSLEndpoint updateVideoCodecs] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_vid_codec_set_priority", referenced from:
      -[VSLEndpoint updateVideoCodecs] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_vid_codec_set_param", referenced from:
      -[VSLEndpoint updateVideoCodecs] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjmedia_endpt_get_codec_mgr", referenced from:
      -[VSLEndpoint getPjMediaCodecManager] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_acc_is_valid", referenced from:
      -[VSLAccount isAccountValid] in libVialerSIPLib.a(VSLAccount.o)
  "_pjmedia_codec_opus_get_config", referenced from:
      -[VSLEndpoint updateOpusSettings:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjmedia_codec_mgr_find_codecs_by_id", referenced from:
      -[VSLEndpoint updateOpusSettings:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_enum_codecs", referenced from:
      -[VSLEndpoint updateAudioCodecs] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_codec_set_priority", referenced from:
      -[VSLEndpoint updateAudioCodecs] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_acc_add", referenced from:
      -[VSLAccount configureWithAccountConfiguration:error:] in libVialerSIPLib.a(VSLAccount.o)
  "_pjsua_destroy", referenced from:
      -[VSLEndpoint destroyPJSUAInstance] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_call_get_info", referenced from:
      -[VSLCall initInboundCallWithCallId:account:] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCall connectDuration] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCall checkIfAudioPresent] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCall toggleMute:] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCall calculateStats] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCallStats generate] in libVialerSIPLib.a(VSLCallStats.o)
      _onIncomingCall in libVialerSIPLib.a(VSLEndpoint.o)
      ...
  "_pjsua_create", referenced from:
      -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_transport_get_info", referenced from:
      -[VSLEndpoint callDealloc:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_logging_config_default", referenced from:
      -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_config_default", referenced from:
      -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_vid_codec_get_param", referenced from:
      -[VSLEndpoint updateVideoCodecs] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_transport_create", referenced from:
      -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjmedia_port_destroy", referenced from:
      -[VSLRingback dealloc] in libVialerSIPLib.a(VSLRingback.o)
  "_pjsua_set_no_snd_dev", referenced from:
      -[VSLAudioController activateSoundDevice] in libVialerSIPLib.a(VSLAudioController.o)
      -[VSLAudioController deactivateSoundDevice] in libVialerSIPLib.a(VSLAudioController.o)
      -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_media_config_default", referenced from:
      -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_start", referenced from:
      -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_call_reinvite2", referenced from:
      -[VSLCall reinvite] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCall toggleHold:] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_call_dial_dtmf", referenced from:
      -[VSLCall sendDTMF:error:] in libVialerSIPLib.a(VSLCall.o)
  "_pj_str", referenced from:
      -[VSLCall sendDTMF:error:] in libVialerSIPLib.a(VSLCall.o)
      -[VSLRingback init] in libVialerSIPLib.a(VSLRingback.o)
      -[NSString(PJString) pjString] in libVialerSIPLib.a(NSString+PJString.o)
  "_pjsua_call_hangup", referenced from:
      -[VSLCall hangup:] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_call_get_stream_info", referenced from:
      -[VSLCallStats generate] in libVialerSIPLib.a(VSLCallStats.o)
  "_pjmedia_codec_mgr_get_default_param", referenced from:
      -[VSLEndpoint updateOpusSettings:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_call_get_stream_stat", referenced from:
      -[VSLCall checkIfAudioPresent] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCallStats generate] in libVialerSIPLib.a(VSLCallStats.o)
  "_pjsua_transport_config_default", referenced from:
      -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_conf_connect", referenced from:
      -[VSLCall mediaStateChanged:] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCall toggleMute:] in libVialerSIPLib.a(VSLCall.o)
      -[VSLRingback start] in libVialerSIPLib.a(VSLRingback.o)
  "_pjsua_acc_set_registration", referenced from:
      -[VSLAccount registerAccountWithCompletion:] in libVialerSIPLib.a(VSLAccount.o)
      -[VSLAccount unregisterAccount:] in libVialerSIPLib.a(VSLAccount.o)
  "_pjmedia_codec_opus_set_default_param", referenced from:
      -[VSLEndpoint updateOpusSettings:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_call_send_request", referenced from:
      -[VSLCall sendDTMF:error:] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_init", referenced from:
      -[VSLEndpoint startEndpointWithEndpointConfiguration:error:] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_call_answer", referenced from:
      -[VSLCall setCallState:] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCall decline:] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_conf_disconnect", referenced from:
      -[VSLCall toggleMute:] in libVialerSIPLib.a(VSLCall.o)
      -[VSLRingback stop] in libVialerSIPLib.a(VSLRingback.o)
  "_pj_pool_release", referenced from:
      -[VSLEndpoint destroyPJSUAInstance] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_pool_create", referenced from:
      -[VSLEndpoint createPoolForPJSIP] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_call_answer2", referenced from:
      -[VSLCall answerWithCompletion:] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_call_update2", referenced from:
      -[VSLCall update] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_conf_add_port", referenced from:
      -[VSLRingback init] in libVialerSIPLib.a(VSLRingback.o)
  "_pj_thread_register", referenced from:
      -[VSLAudioController checkCurrentThreadIsRegisteredWithPJSUA] in libVialerSIPLib.a(VSLAudioController.o)
      -[VSLEndpoint createPJSIPThreadWithError:] in libVialerSIPLib.a(VSLEndpoint.o)
      -[VSLEndpoint destroyPJSUAInstance] in libVialerSIPLib.a(VSLEndpoint.o)
      -[VSLRingback checkCurrentThreadIsRegisteredWithPJSUA] in libVialerSIPLib.a(VSLRingback.o)
      -[VSLAccount checkCurrentThreadIsRegisteredWithPJSUA] in libVialerSIPLib.a(VSLAccount.o)
  "_pjsua_call_xfer_replaces", referenced from:
      -[VSLCall transferToCall:] in libVialerSIPLib.a(VSLCall.o)
  "_pj_thread_is_registered", referenced from:
      -[VSLAudioController checkCurrentThreadIsRegisteredWithPJSUA] in libVialerSIPLib.a(VSLAudioController.o)
      -[VSLEndpoint createPJSIPThreadWithError:] in libVialerSIPLib.a(VSLEndpoint.o)
      -[VSLEndpoint destroyPJSUAInstance] in libVialerSIPLib.a(VSLEndpoint.o)
      -[VSLRingback checkCurrentThreadIsRegisteredWithPJSUA] in libVialerSIPLib.a(VSLRingback.o)
      -[VSLAccount checkCurrentThreadIsRegisteredWithPJSUA] in libVialerSIPLib.a(VSLAccount.o)
  "_pjsua_call_set_hold", referenced from:
      -[VSLCall toggleHold:] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_get_pjmedia_endpt", referenced from:
      -[VSLEndpoint getPjMediaCodecManager] in libVialerSIPLib.a(VSLEndpoint.o)
  "_pjsua_call_xfer", referenced from:
      -[VSLCall blindTransferCallWithNumber:] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_call_make_call", referenced from:
      -[VSLCall startWithCompletion:] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_call_setting_default", referenced from:
      -[VSLCall startWithCompletion:] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCall reinvite] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCall update] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCall answerWithCompletion:] in libVialerSIPLib.a(VSLCall.o)
      -[VSLCall toggleHold:] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_msg_data_init", referenced from:
      -[VSLCall sendDTMF:error:] in libVialerSIPLib.a(VSLCall.o)
  "_pjsua_set_snd_dev", referenced from:
      -[VSLAudioController activateSoundDevice] in libVialerSIPLib.a(VSLAudioController.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

### Other info

Xcode Version 11.4 beta (11N111s)
Device iPhone X iOS 13.4 (17E5241d)

**Comment by ludivinefafournoux** [comment]
I forgot to restart my iMac. Now it works. Thanks

**Comment by fukemy** [comment]
restarted but still no luck to me

**Comment by karanmoon** [comment]
**Facing same issue, somebody please help ASAP.**

--end msg--
💚 DEBUG   19:53:07.824 [VSLCall -[VSLCall checkIfAudioPresent]:469] Unable to check if audio present no active stream!
💚 DEBUG   19:53:09.826 [VSLCall -[VSLCall checkIfAudioPresent]:469] Unable to check if audio present no active stream!
💚 DEBUG   19:53:11.824 [VSLCall -[VSLCall checkIfAudioPresent]:469] Unable to check if audio present no active stream!
💚 DEBUG   19:53:13.824 [VSLCall -[VSLCall checkIfAudioPresent]:469] Unable to check if audio present no active stream!
💚 DEBUG   19:53:15.825 [VSLCall -[VSLCall checkIfAudioPresent]:469] Unable to check if audio present no active stream!
💚 DEBUG   19:53:17.826 [VSLCall -[VSLCall checkIfAudioPresent]:469] Unable to check if audio present no active stream!
💚 DEBUG   19:53:19.824 [VSLCall -[VSLCall checkIfAudioPresent]:469] Unable to check if audio present no active stream!
💚 DEBUG   19:53:21.823 [VSLCall -[VSLCall checkIfAudioPresent]:469] Unable to check if audio present no active stream!
💚 DEBUG   19:53:22.507 [VSLEndpoint void logCallBack(int, const char *, int):567]           pjsua_core.c  .RX 954 bytes Request msg INVITE/cseq=13128 (rdata0x103813028) from UDP 54.69.214.117:5060:
