### ISSUE TITLE
Auto Answer for Incoming Call

### ISSUE THREAD

**Issue by krishnastvSMSC** [VoIPGRID/VialerSIPLib#226]
Hello Team,

I need to auto answer my incoming call without callkit interaction. I tried with `- (void)answerWithCompletion:(void (^ _Nullable)(NSError * _Nullable error))completion;` form VSLCall class. Call is answer but no media is transmitting. Any one help me to resolve this issue. Thank you

**Comment by fukemy** [comment]
my audio session were activated bu still no sound, can u help?

**Comment by karanmoon** [comment]
Can someone please help here...
