### ISSUE TITLE
Need help with Vialer

### ISSUE THREAD

**Issue by showenemytime** [VoIPGRID/VialerSIPLib#240]
Hello. 
We are developing a video calling app using PJSIP and Vialer.
We use the latest available versions of libraries that have not changed for a long time. 
https://github.com/VoIPGRID/Vialer-pjsip-iOS, 
https://github.com/VoIPGRID/VialerSIPLib

Environment: 
Xcode: checked the versions 10, 11, 12
Mac OS 10.15.6 and newer

In the last 2 months, we have had difficulties with the remake build Vialer-pjsip-iOS. 
The vialerbuild script seems works fine, but we see the warnings in the process of migration
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning for architecture: armv7 same member name (audiodev.o) in output file used for input files: ./pjsip/temp/armv7/libpjmedia-audiodev-armv7-apple-darwin_ios.a(audiodev.o) and:
and the file size is half as much as it was before and build does not work in Xcode. 

Xcode shows error 
Undefined symbols for architecture arm64:
  "_pjsua_vid_dev_set_setting", referenced from:

Did you have this kind of problem? Will you check it, please? 

P.S.
For convenience, we put test projects and libraries (unchanged) together
https://github.com/YSavitskiy/vialer-updates

Telegram for communication @showenemytime

**Comment by ashwani280496** [comment]
@showenemytime  did you find solution?

**Comment by showenemytime** [comment]
yes, the decision came by itself

**Comment by ashwani280496** [comment]
@showenemytime could you please help me to make it build?
