### ISSUE TITLE
Crash - Registering user.

### ISSUE THREAD

**Issue by Nagamuni10** [VoIPGRID/VialerSIPLib#248]
### Version

3.7.3

### File / Feature

Resgestering SIP user. 
![Screenshot 2022-02-08 at 5 22 27 PM](https://user-images.githubusercontent.com/88760478/152981814-13f019ee-051d-4b90-b472-876624f6b5a6.png)

### Actual behavior
When i tried to register a sip account, I got this crash :
Assertion failed: (pjsua_var.tpdata[0].data.ptr != ((void*)0)), function pjsua_acc_add, file ../src/pjsua-lib/pjsua_acc.c, line 439.

### Stacktrace / Error message
Assertion failed: (pjsua_var.tpdata[0].data.ptr != ((void*)0)), function pjsua_acc_add, file ../src/pjsua-lib/pjsua_acc.c, line 439.

**Comment by Nagamuni10** [comment]
Using UDP
17:37:46.935         os_core_unix.c !pjlib 2.10 for POSIX initialized
17:37:46.939         sip_endpoint.c  .Creating endpoint instance...
17:37:46.942                  pjlib  .select() I/O Queue created (0x1048f8028)
17:37:46.943         sip_endpoint.c  .Module "mod-msg-print" registered
17:37:46.944        sip_transport.c  .Transport manager created.
17:37:46.944           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
2022-02-08 17:37:47.068261+0530 Akorbi[788:163984] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2022-02-08 17:37:47.070557+0530 Akorbi[788:163984] [MC] Reading from public effective user settings.
<DDLogMessage: 0x283898b40>
<DDLogMessage: 0x28389c000>
<DDLogMessage: 0x28389c000>
<DDLogMessage: 0x28389c000>
**Could not create account. Error:Error Domain=VialerSIPLib.VSLAccount Code=0 "Could not configure VSLAccount" UserInfo={NSLocalizedDescription=Could not configure VSLAccount, NSLocalizedFailureReason=PJSIP status code: 171039}**
Exiting
Assertion failed: file Akorbi/AppDelegate.swift, line 226
2022-02-08 17:37:55.640955+0530 Akorbi[788:163984] Assertion failed:

Now I am getting this error. Can someone help on this?

**Comment by Vasilich1984** [comment]
Hi,
had you chance to found solution?
I get the same issue after updated to iOS 16. 
Reboot of iPhone helps but some weeks later appears again

**Comment by Nagamuni10** [comment]
Hi, 
It is issue with the network. It is a random crash happens randomly with different networks. To fix that you need to change the contactrewrite method to re-register in the vslaccountconfiguration file. Don't know how but that will solve the crash issue permanently.
