### ISSUE TITLE
'VialerSIPLib/CallKitProviderDelegate.h' file not found

### ISSUE THREAD

**Issue by Victor1506** [VoIPGRID/VialerSIPLib#33]
When I install (pod 'VialerSIPLib") in my swift project and trying to import classes via Bridging-Header I get error 'VialerSIPLib/CallKitProviderDelegate.h' and VialerSIPLib/VSLAudioController.h file not found.

**Comment by vkrotin** [comment]
I had the same problem. I think it's because release version (2.0.0) has not been pushed on CocoaPods, now there is a version 1.0.6 on https://libraries.io/cocoapods/VialerSIPLib

**Comment by bobvoorneveld** [comment]
I checked cocoapods again, but it is on the newest version (2.0.1):
https://cocoapods.org/pods/VialerSIPLib

The url @vkrotin provided has outdated information.

@Victor1506 can you check in your installed pod if the files are present? Maybe a pod deintegrate might help
