### ISSUE TITLE
Not able to register or call

### ISSUE THREAD

**Issue by mital87** [VoIPGRID/VialerSIPLib#35]
Hello Team,

I have used my own credential in the example and execute it. But nothing after **setupVialerEndpoint** method call. please my log shown in below :

**My Logs:**

```
17:25:13.568 os_core_unix.c !pjlib 2.5.5-svn for POSIX initialized

17:25:13.569 sip_endpoint.c  .Creating endpoint instance...

17:25:13.571  pjlib  .select() I/O Queue created (0x7f9f8283ea28)

17:25:13.572 sip_endpoint.c  .Module "mod-msg-print" registered

17:25:13.572 sip_transport.  .Transport manager created.

17:25:13.572   pjsua_core.c  .PJSUA state changed: NULL --> CREATED

WARNING: no real random source present!
```
then after i am not able to register or call.

Any help would be appreciated! thanks

**Comment by mital87** [comment]
@bobvoorneveld & @smolskyaleksey: I am spending 4-5 days but didn't get any success from my end. Please help me to resolve this issue. Thanks in advance.

**Comment by bobvoorneveld** [comment]
Hi @mital87. have you any succes with other sip applications to register at your sip server? Have you got a stacktrace when you try to register?

**Comment by mital87** [comment]
@bobvoorneveld: Thanks for the reply.

I am using X-Lite (powered by CounterPath) Application. Using this application I am successfully registered with the SIP Server. But When I am trying with latest our example with my SIP details I have not registered my extension. Thanks in advance.

**Comment by bobvoorneveld** [comment]
Do you have a trace of the app?

**Comment by mital87** [comment]
Nothing happened after **setupVialerEndpoint** method Call.

**My Logs:**

```
17:25:13.568 os_core_unix.c !pjlib 2.5.5-svn for POSIX initialized

17:25:13.569 sip_endpoint.c .Creating endpoint instance...

17:25:13.571 pjlib .select() I/O Queue created (0x7f9f8283ea28)

17:25:13.572 sip_endpoint.c .Module "mod-msg-print" registered

17:25:13.572 sip_transport. .Transport manager created.

17:25:13.572 pjsua_core.c .PJSUA state changed: NULL --> CREATED

WARNING: no real random source present!
```
What can I do? Only above logs prints in the console. 

then click on the register button, nothing happened. as well as no register completion block call.

**Comment by bobvoorneveld** [comment]
try to put in some breakpoints in the registerAccountWithcompletion to see what is happening, should work...

**Comment by mital87** [comment]
@bobvoorneveld: when I have put the breakpoint in the registerAccountWithcompletion, I found that self.accountId was null. so what can i do?

**Comment by mital87** [comment]
@bobvoorneveld: please help me to resolve my issue. I am not found any solution regarding this.

**Comment by mital87** [comment]
@bobvoorneveld & @smolskyaleksey : What is the meaning of "WARNING: no real random source present!" statement?

**Comment by bobvoorneveld** [comment]
Last check, did you add the Keys.swift file to the target? Otherwise it will not know the the file...
![screen shot 2017-01-11 at 08 09 20](https://cloud.githubusercontent.com/assets/6303073/21838944/5b3a4c92-d7d5-11e6-95a1-2f0d4299ea6b.png)

The real random source is not related to your problem, the warning is also in our project. This shouldn't be an issue if you're not working on secure calling. This will probably be fixed when we start working on secure calling, because encryption relies on a real random source.

**Comment by mital87** [comment]
I have attached screen shots, please look into that. Please help me.

**1. SIP Credential**

![sip credential](https://cloud.githubusercontent.com/assets/4548715/21839673/0a8d9b8a-d7ff-11e6-8a93-ac25773ee7bd.png)

**2. AppDelegate - setupVialerEndpoint method**

![appdelegate](https://cloud.githubusercontent.com/assets/4548715/21839678/0e7d10f4-d7ff-11e6-9e30-753dff8c3338.png)

**3. Register Action & Output**

![vslmainvc](https://cloud.githubusercontent.com/assets/4548715/21839679/11b49ea4-d7ff-11e6-93c6-81823c646334.png)

**Comment by bobvoorneveld** [comment]
can you put your code somewhere on github?

**Comment by smolskyaleksey** [comment]
Did you add to Info.plist ?

```
<key>NSAppTransportSecurity</key>
	<dict>
            <key>NSAllowsArbitraryLoads</key>
            <true/>
       </dict>
```

**Comment by davydov-denis** [comment]
I have the same problem. But don't have warnings. Just build the example and register and call isn't able. Please help!

**Comment by mital87** [comment]
@bobvoorneveld: This is my GitHub link: (https://github.com/mital87/VialerSIPLib). Please help me as soon as possible.

@smolskyaleksey: Ya I have already done that thing in my code.

**Comment by smolskyaleksey** [comment]
http://pastebin.com/aYQYUP7Y
Pls see my logs.Your example is absolutely correct.

**Comment by davydov-denis** [comment]
Maybe Keys.swift configuration isn't correct?
I saw the unit tests and seems my configuration is correct, and the account too.

> DEBUG   11:52:32.449 [VSLAccount -[VSLAccount registerAccountWithCompletion:]:168] Account valid: YES

But the registration is not able and calls isn't too.

Do someone have any ideas?

**Comment by mital87** [comment]
@smolskyaleksey: With my SIP Details, I am not able to register on SIP server. so what can I do to resolve my issue? Please help me.

**Comment by davydov-denis** [comment]
Help us please!

**Comment by mital87** [comment]
@bobvoorneveld & @smolskyaleksey : @davydov-denis & me, both are facing the same issue. we can't able to register or make a call. Please help us as soon as possible.

**Comment by bobvoorneveld** [comment]
hmm, I just did a checkout of your code, added my sip credentials in the Keys.swift file and it worked. So if you didn't change anything to the code that is on your repo (master branch), I cannot see whats going wrong...

**Comment by bobvoorneveld** [comment]
@mital87 if I look at your console log, the endpoint is never started. Did you change anything in de AppDelegate that is not on github? Have you put in a breakpoint in `setupVialerEndpoint` to see if the endpoint is being setup?

**Comment by davydov-denis** [comment]
@bobvoorneveld in this case, сuriously. I didn't change anything of the code excluding Keys.swift and Info.plist. Exactly, I cloned master branch. So, we absolutely don't know how to fix that.

**Comment by bobvoorneveld** [comment]
what device are you running?

**Comment by smolskyaleksey** [comment]
@davydov-denis username have to be without any suffix only number, not like this "username2@XXX.XXX.X.XXX". Only username2

**Comment by davydov-denis** [comment]
@smolskyaleksey I've tried  `"username2"`but it's didn't work too. 
@bobvoorneveld I'm running on iPad MC773LL/A.

**Comment by bobvoorneveld** [comment]
have you tried iPhone simulator?

**Comment by mital87** [comment]
@bobvoorneveld: I did put only **SIP Details** in **Key.swift** File. I am using the simulator for same.

**Comment by bobvoorneveld** [comment]
iPhone simulator? And the breakpoint, does the code get executed on setupVialerEndpoint?

**Comment by mital87** [comment]
@bobvoorneveld : **iPhone 7 plus Simulator (iOS -10.2)**. **"setupVialerEndpoint"** method is executes but not initialize endpoints.

**Comment by bobvoorneveld** [comment]
Did you step trough every line of code of `- (BOOL)configureLibraryWithEndPointConfiguration:(VSLEndpointConfiguration * _Nonnull)endpointConfiguration error:(NSError * _Nullable * _Nullable)error;` and saw something strange?

**Comment by mital87** [comment]
@bobvoorneveld: i will get success on this method but didn't get any log. so please tell me how can i start my debug log for this.

**Comment by davydov-denis** [comment]
@bobvoorneveld Yes, I've tried simulator.
I am debugging that now but don't see till something strange.

**Comment by mital87** [comment]
@davydov-denis : you have got any log? or how can you start debug log?

**Comment by davydov-denis** [comment]
@mital87 no, I haven't. I started only debug but I don't know how I can get debug log.

**Comment by mital87** [comment]
@bobvoorneveld: what can we do now? how can we resolve this issue? Please help us to resolve this issue ASAP.

**Comment by bobvoorneveld** [comment]
I'm a bit out of options. Is it possible to give me your (temporary) credentials? I'll check again. But your source code works on this side. plz email them to: bob.voorneveld@wearespindle.com

**Comment by mital87** [comment]
@bobvoorneveld, @smolskyaleksey, @davydov-denis: When i have clicked to Register Button, i was getting below logs.

**My Logs:**

```
DEBUG [VSLEndpoint -[VSLEndpoint startEndpointWithEndpointConfiguration:error:]:124] Creating new PJSIP Endpoint instance.

09:39:59.036 os_core_unix.c !pjlib 2.5.5-svn for POSIX initialized

09:39:59.039 sip_endpoint.c .Creating endpoint instance...

09:39:59.043 pjlib .select() I/O Queue created (0x7f86f9005c28)

09:39:59.043 sip_endpoint.c .Module "mod-msg-print" registered

09:39:59.044 sip_transport. .Transport manager created.

09:39:59.044 pjsua_core.c .PJSUA state changed: NULL --> CREATED

WARNING: no real random source present!

INFO [VSLEndpoint void logCallBack(int, const char *, int):448] pjsua_core.c .pjsua version 2.5.5-svn for Darwin-16.3/x86_64 initialized

INFO [VSLEndpoint -[VSLEndpoint startEndpointWithEndpointConfiguration:error:]:230] PJSIP Endpoint started succesfully

INFO [VSLAccount -[VSLAccount configureWithAccountConfiguration:error:]:135] Account added succesfully

DEBUG [VSLAccount -[VSLAccount registerAccountWithCompletion:]:168] Account valid: YES

VERBOSE [VSLAccount -[VSLAccount registerAccountWithCompletion:]:178] Sending registration for account: 0

VERBOSE [VSLEndpoint void onRegStarted2(pjsua_acc_id, pjsua_reg_info *):495] onRegStarted2

INFO [VSLEndpoint void onRegStarted2(pjsua_acc_id, pjsua_reg_info *):504] Saving transport

WARNING [VSLEndpoint void logCallBack(int, const char *, int):445] pjsua_acc.c !...SIP registration failed, status=408 (Request Timeout)

VERBOSE [VSLEndpoint void onRegState2(pjsua_acc_id, pjsua_reg_info *):511] onRegState2

DEBUG [VSLEndpoint void releaseStoredTransport():564] Releasing transport

DEBUG [VSLAccount -[VSLAccount setAccountState:]:53] AccountState will change from VSLAccountStateOffline(0) to VSLAccountStateDisconnected(3)

VERBOSE [VSLEndpoint void onRegStarted2(pjsua_acc_id, pjsua_reg_info *):495] onRegStarted2

INFO [VSLEndpoint void onRegStarted2(pjsua_acc_id, pjsua_reg_info *):504] Saving transport

WARNING [VSLEndpoint void logCallBack(int, const char *, int):445] pjsua_acc.c ...SIP registration failed, status=408 (Request Timeout)

INFO [VSLEndpoint void logCallBack(int, const char *, int):448] pjsua_call.c ....Invalid call_id 0 in pjsua_call_hangup()

INFO [VSLEndpoint void logCallBack(int, const char *, int):448] pjsua_call.c ....Invalid call_id 1 in pjsua_call_hangup()

INFO [VSLEndpoint void logCallBack(int, const char *, int):448] pjsua_call.c ....Invalid call_id 2 in pjsua_call_hangup()

INFO [VSLEndpoint void logCallBack(int, const char *, int):448] pjsua_call.c ....Invalid call_id 3 in pjsua_call_hangup()

INFO [VSLEndpoint void logCallBack(int, const char *, int):448] pjsua_acc.c ...Disconnecting 4 call(s) of account #0 after reregistration attempt failed

VERBOSE [VSLEndpoint void onRegState2(pjsua_acc_id, pjsua_reg_info *):511] onRegState2

DEBUG [VSLEndpoint void releaseStoredTransport():564] Releasing transport

INFO [VSLEndpoint void logCallBack(int, const char *, int):448] tcpc0x7f86fa84 TCP connect() error: Operation timed out [code=120060]

VERBOSE [VSLEndpoint void onTransportState(pjsip_transport *, pjsip_transport_state, const pjsip_transport_state_info *):527] onTransportState

VERBOSE [VSLEndpoint void onTransportState(pjsip_transport *, pjsip_transport_state, const pjsip_transport_state_info *):527] onTransportState
```

So what was the **wrong** in this log? Please help me to resolve this issue ASAP.

**Comment by smolskyaleksey** [comment]
You have time out response 

WARNING [VSLEndpoint void logCallBack(int, const char *, int):445] pjsua_acc.c ...SIP registration failed, status=408 (Request Timeout)


Pls , check your server side.

**Comment by mital87** [comment]
@smolskyaleksey: I have used same SIP Credential in X-Lite App (PoweredBy CounterPath). This is working fine. @Davydov-denis has also used their SIP Credential in Gossip App and that is also working fine.

So @Me & @davydov-denis, facing the same issue. so how can we resolve this thing? Please help us.

**Comment by mital87** [comment]
@bobvoorneveld & @smolskyaleksey: I think so this is transport connection (ie. UDP / TCP ) issue. 

When I was debugging **onRegStarted2** method, I found that 

`"info = 0x00007f9c028361b0 "TCP to 27.111.250.***:5060""`

then after i have got

`WARNING [VSLEndpoint void logCallBack(int, const char *, int):445] pjsua_acc.c !...SIP registration failed, status=408 (Request Timeout). `

so TCP Connection hasn't established with SIP Server. so,

`INFO [VSLEndpoint void logCallBack(int, const char *, int):449] tcpc0x7f949084 TCP connect() error: Operation timed out [code=120060]`

Is there any way to connect with **UDP transport**?

Please help me ASAP.

**Comment by spindleredmer** [comment]
You can use UDP Transport by doing this.
```
let endpointConfiguration = VSLEndpointConfiguration()
endpointConfiguration.logLevel = 3
endpointConfiguration.userAgent = "VialerSIPLib Example App"
endpointConfiguration.transportConfigurations = [VSLTransportConfiguration(transportType: .UDP)!]
```

**Comment by davydov-denis** [comment]
@bobvoorneveld I think this is a **TCP** issue.
`VERBOSE 10:35:37.165 [VSLAccount -[VSLAccount registerAccountWithCompletion:]:178] Sending registration for account: 0`
`VERBOSE 10:35:37.174 [VSLEndpoint void onRegStarted2(pjsua_acc_id, pjsua_reg_info *):495] onRegStarted2`
`INFO    10:35:37.175 [VSLEndpoint void onRegStarted2(pjsua_acc_id, pjsua_reg_info *):504] Saving transport`
`INFO    10:35:37.182 [VSLEndpoint void logCallBack(int, const char *, int):448] tcpc0x17393614 !TCP connect() error: Connection refused [code=120061]`
`INFO    10:35:37.182 [VSLEndpoint void logCallBack(int, const char *, int):448]  tsx0x17394a64  Failed to send Request msg REGISTER/cseq=46739 (tdta0x17391400)! err=120061 (Connection refused)`
`WARNING 10:35:37.183 [VSLEndpoint void logCallBack(int, const char *, int):445]    pjsua_acc.c  ..SIP registration failed, status=503 (Connection refused)`

I don't know whats happened, but server working fine. It was tested on Gossip iOS, a few times on android, on desktop.

**Comment by davydov-denis** [comment]
@spindleredmer Thank you, I will try this now.

**Comment by mital87** [comment]
@bobvoorneveld , @smolskyaleksey , @spindleredmer , @davydov-denis : This is woking fine.
Thank you so much....!!!

**Comment by mital87** [comment]
@davydov-denis: Have you face any calling issue after removing **TCP** connection in transportConfigurations?

**Comment by bkr1989** [comment]
Hi @mital87  i am also facing the same issue like.." CallState will change from VSLCallStateEarly(3) to VSLCallStateDisconnected(6)"... did u find any solution for the problem you mentioned?.... if iso please help me with your solution...

**Comment by bkr1989** [comment]
Hi @bobvoorneveld  can you please me in this?

**Comment by mital87** [comment]
Hi @bkr1989,

Can you please elaborate your issue in deep? So I will help you to figure out this issue.

**Comment by bobvoorneveld** [comment]
@bkr1989, I'm no longer working on this project

**Comment by bkr1989** [comment]
@bobvoorneveld  ..ok thanks..anyway i have solved  the issue

**Comment by siddhartha-shi** [comment]
@bkr1989 I am also facing calls disconnecting issue, please help me with that problem. How did you solve the issue?
