### ISSUE TITLE
Keep the connection alive when not calling

### ISSUE THREAD

**Issue by mital87** [VoIPGRID/VialerSIPLib#36]
Hello Team,

I drop the connection once the application is ideal or not calling to anyone. so please help me to resolve this issue.

Any help would be appreciated! thanks.

**Comment by bobvoorneveld** [comment]
I don't really understand what your problem is. Could you explain more in detail what your goal is and what you problem is?

**Comment by mital87** [comment]
@bobvoorneveld: Thanks for the reply.

When I was successfully registered in the application. after few seconds my connection is dropped (ie extension is unregistered). So I have not received any calls or not call on the specific extension on my VoIP server. If you like more elaborate this thing then let me know but please help me to figure out this issue.

**Comment by bobvoorneveld** [comment]
@mital87, this is what iOS does. You need to put in a system that will register just before the call will start to invite. We use a middleware that pushes a notification to the app, the app will register and inform de middleware that the call can be put through. See:
https://github.com/VoIPGRID/vialer-middleware

You can see our implementation is our production app:
https://github.com/VoIPGRID/vialer-ios
