### ISSUE TITLE
Crash in disconnectedSoundPlayer

### ISSUE THREAD

**Issue by Victor1506** [VoIPGRID/VialerSIPLib#44]
I dragged library into my swift project, imported it through bridging-header and it works fine. But sometimes I get a crash in disconnectedSoundPlayer.

#5. Crashed: com.twitter.crashlytics.ios.exception
0  MyApp           0x26c8b7 CLSProcessRecordAllThreads + 992
1  MyApp           0x26c8b7 CLSProcessRecordAllThreads + 992
2  MyApp           0x26c7af CLSProcessRecordAllThreads + 728
3  MyApp           0x2607f7 CLSHandler + 30
4  MyApp           0x26b0c7 __CLSExceptionRecord_block_invoke + 66
5  libdispatch.dylib              0x1af82083 _dispatch_client_callout + 22
6  libdispatch.dylib              0x1af8e33b _dispatch_barrier_sync_f_invoke + 50
7  MyApp           0x26aac9 CLSExceptionRecord + 252
8  MyApp           0x26a8f1 CLSExceptionRecordNSException + 600
9  MyApp           0x26a407 CLSTerminateHandler() + 326
10 libc++abi.dylib                0x1ab3393f std::__terminate(void (*)()) + 78
11 libc++abi.dylib                0x1ab3314f __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 110
12 libobjc.A.dylib                0x1ab3f149 _objc_exception_destructor(void*) + 246
13 CoreFoundation                 0x1b8dcd3d -[NSException initWithCoder:] + 106
14 Foundation                     0x1c1a91d3 -[NSBundle initWithURL:] + 88
15 Foundation                     0x1c1a9167 +[NSBundle bundleWithURL:] + 42
16 MyApp           0xa799b -[VSLCall disconnectedSoundPlayer] (VSLCall.m:240)
17 MyApp           0xa6aa3 -[VSLCall setCallState:] (VSLCall.m:153)
18 MyApp           0xa8111 -[VSLCall updateCallInfo:] (VSLCall.m:293)
19 MyApp           0xa847d -[VSLCall callStateChanged:] (VSLCall.m:307)
20 MyApp           0xa26df onCallState (VSLEndpoint.m:468)
21 MyApp           0x360423 pjsua_call_on_state_changed + 846

**Comment by bobvoorneveld** [comment]
can you add a bigger crashlog? Do you know on which thread this is happening?

We saw some issues if the incoming callblock was not dispatched to the main queue, which gave problems with the callmanager from iOS. Make sure every action is happening on the main queue, that might prevent these crashes.

**Comment by Victor1506** [comment]
My Logs:

[Uploading log.txt…]()

**Comment by Victor1506** [comment]
My Logs:
[log.txt](https://github.com/VoIPGRID/VialerSIPLib/files/714200/log.txt)

**Comment by bobvoorneveld** [comment]
It is looking for a disconnected.wav in VialerSIPLib bundle. It seems to be broken when getting the correct bundle:
```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1b8dcdf7 __exceptionPreprocess
1  libobjc.A.dylib                0x1ab3f077 objc_exception_throw
2  CoreFoundation                 0x1b8dcd3d -[NSException initWithCoder:]
3  Foundation                     0x1c1a91d3 -[NSBundle initWithURL:]
4  Foundation                     0x1c1a9167 +[NSBundle bundleWithURL:]
5  MyApp           0x287bb -[VSLCall disconnectedSoundPlayer] (VSLCall.m:240)
```

Did you use another way of installing than using cocoapods?

**Comment by Victor1506** [comment]
I linked library as module, because I needed to use frameworks in pods

**Comment by bobvoorneveld** [comment]
So it has a problem finding the correct bundle. If you can come up with a solution to find another way to find the disconnect.wav, that problem should not occur anymore...

**Comment by Victor1506** [comment]
Thanks!
