### ISSUE TITLE
Not Receiving Incoming Call 

### ISSUE THREAD

**Issue by mital87** [VoIPGRID/VialerSIPLib#45]
@bobvoorneveld, @spindleredmer: 

I am not able to receive any **incoming calls** in our **VialerSIPLib example**. So how can i achieve this in our example app? Please help me to resolve this thing ASAP. Do needful.

Thanking you.

**Comment by mital87** [comment]
@bobvoorneveld, @spindleredmer: Is there any example for **Vialer Middleware** in **iOS**? I have stuck here. Can you please guide me to resolve this thing ASAP. Do needful.

**Comment by bobvoorneveld** [comment]
Hi @mital87, as answered by @m-vellinga, the solution can be found here:
https://github.com/VoIPGRID/vialer-middleware/issues/2

If you would like to see how we integrated that part, please check:
https://github.com/VoIPGRID/vialer-ios/blob/develop/Vialer/APNS/APNSHandler.m
https://github.com/VoIPGRID/vialer-ios/blob/develop/Vialer/Middleware/Middleware.m

**Comment by mital87** [comment]
@bobvoorneveld: Thanks for the reply. Instead of that, required any other **changes** or **settings** in the application?

**Comment by bobvoorneveld** [comment]
Make sure that the capabilities are set correct:
![screen shot 2017-01-18 at 11 50 49](https://cloud.githubusercontent.com/assets/6303073/22061248/685132fc-dd74-11e6-9795-9698605d4509.png)

**Comment by mital87** [comment]
@bobvoorneveld: Is this possible to receive the **incoming call** without implement **Vialer Middleware**? Please reply me as soon as possible.

**Comment by bobvoorneveld** [comment]
The whole setup of this library is so that there is need of some sort of middleware. This is to save battery life and to make sure the registration is always correct when there is an incoming call. This library was never intended to work without some sort of middleware.

**Comment by mital87** [comment]
@bobvoorneveld: thanks for the reply. 

I have followed below steps to receive Incoming Calls.

1. Setup **Vialer Middleware** on **My Server.**
2. Put **APNSHandler & Middleware** folder in Example app.
3. Set the capabilities like background modes & push notification.
4. **registerForVoIPNotifications** methods implementeed in **didFinishLaunchingWithOptions**

Then which methods i will implement to receiving incoming calls? Please help me.

**Comment by mital87** [comment]
@bobvoorneveld: Please guide me. Waiting for your reply.

**Comment by masiiha** [comment]
@mital87  Problem solved?

**Comment by mital87** [comment]
@masiiha  : Not setup VialerMiddleware on my server.
