### ISSUE TITLE
Is it worked on 3G?

### ISSUE THREAD

**Issue by davydov-denis** [VoIPGRID/VialerSIPLib#48]
Hello guys.

Is VialerSIPlib worked **through the 3G?**
I'm sorry for stupid question, but I can't test it (have only local server) and the _vialer-ios_ can work (as I understand) `> only when connected to Wi-Fi of 4G.`

**Comment by bobvoorneveld** [comment]
The lib will work with any connection available. We believe that a 4G or WiFi connection gives the best result, so we do not accept a call if the connection is otherwise. But this is not a feature of the lib, only from vialer-ios app.

**Comment by davydov-denis** [comment]
@bobvoorneveld Thank you very much <3
