### ISSUE TITLE
How do i give TLS Support ? 

### ISSUE THREAD

**Issue by gizmoboy7** [VoIPGRID/VialerSIPLib#50]
Just wondering if i can give TLS support through the Vialer library

**Comment by bobvoorneveld** [comment]
We currently have no support for TLS. This will be one of the first items that we'll pick up as soon as we have a stable version of the library. We currently still have issues with reconnecting when there are network changes. After that fix, this is the first thing on our roadmap.

The pod Vialer-PJSIP-ios has no SSL support at the moment. That will be the first step.

If you made progress on this, please let us know, so we can speed up the process of implementing secure calling.

**Comment by gizmoboy7** [comment]
I was wondering why I couldn't add TLS Support. There was an `PJSIP_TRANSPORT_TLS` enum in  `siptypes.h`, I thought adding an enum in the `VSLTransportConfiguration.h` should do the trick, since the PJSIP was a .framework file, i couldn't go further on to debug to find the issue. 

So essentially we need to change the sip library, right?

**Comment by bobvoorneveld** [comment]
Yes, that is a start. But recompiling the depended pjsip version is also needed. So it is work on 2 pods before it will work. It is something that we have on our roadmap after we get this project stable and our app that is using this lib stable.
