### ISSUE TITLE
Dealloc Call

### ISSUE THREAD

**Issue by smolskyaleksey** [VoIPGRID/VialerSIPLib#52]
I have stange behaviors after hungup call method  dealloc  doesn't have call and don't have 
`Dealloc Call uuid:<UUID> id:0`
Could you check it on your code? When I call onCallState on main thread is all right.

**Comment by smolskyaleksey** [comment]
If don't call onCallState callback on main thread I found very strange  place 



```
/**
 *  Start the network monitor if the call is not disconnected
 *  which will inform us about a network change so we can bring down
 *  and reinitialize the TCP transport.
 */
- (void)checkNetworkMonitoring:(NSNotification *)notification {
    VSLCall *call = notification.userInfo[VSLNotificationUserInfoCallKey];

    switch (call.callState) {
        case VSLCallStateDisconnected: {
            [self stopNetworkMonitoring];
            break;
        }
        default: {
            if (!self.monitoringCalls) {
                for (VSLAccount *account in self.accounts) {
                    if ([account firstActiveCall]) {
                        DDLogVerbose(@"Starting network monitor");
                        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(ipAddressChanged:) name:VSLNetworkMonitorChangedNotification object:nil];
                        [self.networkMonitor startMonitoring];
                        self.monitoringCalls = YES;
                        break;
                    }
                }
            }
        }
    }
}
```
If i call this method on main thread is all right and I get `Dealloc Call uuid:<UUID> id:0`, but if it is called in same thread where post notification, i don't get `Dealloc Call uuid:<UUID> id:0`.
Do you have amy idea why?
Definitely problem in   `if ([account firstActiveCall]) `

**Comment by bobvoorneveld** [comment]
Because we're using callkit, I would not recommend using anything other than the main queue for these kind of actions. There probably is a reference to the call somewhere else on a different thread.

**Comment by smolskyaleksey** [comment]
Could you check maybe you have same bug?
