### ISSUE TITLE
'VialerPJSIP/pjsua-lib/pjsua.h' file not found

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [VoIPGRID/VialerSIPLib#65]
When I create a simple project and try to add VialerSIPLib using CocoaPods as shown
```ruby
platform :ios, '9.0'
pod 'VialerSIPLib'
```

I got the **Target has transitive dependencies that include static binaries** error. After using a workaround at [#6036 ](https://github.com/CocoaPods/CocoaPods/issues/6036#issuecomment-253650687) fixed this problem.
```ruby
pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end
```
After that I got another error while building:

> Pods/VialerSIPLib/Pod/Classes/Configurations/VSLAccountConfiguration.h:7:10: 'VialerPJSIP/pjsua-lib/pjsua.h' file not found

However, the file is in `VialerPJSIP.framework`

Trying [pod 'Vialer-pjsip-iOS', :git => 'https://github.com/VoIPGRID/Vialer-pjsip-iOS'](https://github.com/VoIPGRID/VialerSIPLib/issues/4#issuecomment-241737760) did change nothing.

What else should I try?

**Comment by OrkhanAlikhanov** [comment]
The main problem is that we **_cannot_** and **_will not_** be able to use this library alogside with `use_frameworks!`. The bigger problem is that, when I comment out `use_frameworks!`, another problem raises for other swift libraries (for example, [Alamofire](https://github.com/Alamofire/Alamofire))

> Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: Alamofire

**Comment by OrkhanAlikhanov** [comment]
If I kept  `use_frameworks!` and did `installer.verify_no_static_framework_transitive_dependencies` to pass the error. This causes CocoaPods to refuse coping header files into `Pod/Headers` folder.
In order to manually copy the header files I commented out the and did `pod install` copied the `Pod/Headers` folder somewhere, uncommented `use_frameworks!` and did `pod install` again and pasted the header files back to `Pod/Headers`. This fixed the file not found problem, but in this time linker gave error: 

> symbol(s) not found for architecture i386

The [answer](http://stackoverflow.com/a/4840210) states: 

> It usually means the project is missing some frameworks it needs.

I decided to abandon this lib for now... :/

**Comment by OrkhanAlikhanov** [comment]
Just thought, wouldn't manually adding this library to the project work?

**Comment by bobvoorneveld** [comment]
@OrkhanAlikhanov, had you any luck with adding it manually? We could update the project README and give an explanation on how to add it to a Swift project.

**Comment by OrkhanAlikhanov** [comment]
@bobvoorneveld  yes I had successfully added it manually but couldn't find how to receive incoming call, so I went with Gossip.

**Comment by bobvoorneveld** [comment]
the project is designed to only register when you expect an incoming call and not stay registered all the time. This because of battery consumption and the problems you get when the app gets deactivated by the OS when it is in background. In our production app (Vialer), we've build an integration with VoIPPush, and our server will first notify our middleware that will sent a push notification trough the apple network, that will wake up the app, will start a register and then the PBX will sent the call to the sip account.

I'm curious how Gossip helps you better than our lib on that part, maybe we can learn something about that?

**Comment by OrkhanAlikhanov** [comment]
I do understand how VoIP pushes work that's why I kept insisted on using this library. I have read your article somewhere talking about how did you build up this project and what is VoIP for :)

Gossip is simple (at least for me) :) I am using Gossip to just demonstrate the app to project manager ;). I will return to this library after I finish main parts of the code.

**Comment by bobvoorneveld** [comment]
When you return to our lib, please share your troubles, so we can start making the lib easier to use. I'll close this issue.

**Comment by invisible66** [comment]
Could you please how you add it manually?

**Comment by OrkhanAlikhanov** [comment]
@invisible66 As far as I remember:
1. Downloaded the project
2. Add as subfolder to the project
3. `#include <VoiPGRID/blah.h>` to `#include "blah.h"` using regex in all files
4. Bridge objective-c to swift
5. Use it

**Comment by invisible66** [comment]
I will try, thanks.
