### ISSUE TITLE
iOS 8 support?

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [VoIPGRID/VialerSIPLib#66]
What is the main reason of not supporting iOS 8? As far as I know, iOS 8 devices can also register for VoIP Pushes.

**Comment by bobvoorneveld** [comment]
We've looked at our current user base and did see that almost everyone was on iOS9 or newer. And the devices we would like to support had to be 4G phones that work in the Netherlands, our primary user base. That is the iPhone 4s and greater, which is supporting iOS9. That gave us the freedom to implement based on 9 and not take 8 as a base.

Hope that that will answer your questions.

**Comment by OrkhanAlikhanov** [comment]
What does lack in iOS 8 that you don't support it?

**Comment by bobvoorneveld** [comment]
We had no way of testing it, so we don't know, but couldn't say that it would have worked on iOS8...
