### ISSUE TITLE
Compile Error 

### ISSUE THREAD

**Issue by HugoTheBoss** [VoIPGRID/VialerSIPLib#7]
Hello,

when i use your LIB in my existing Project i get compiling Error

duplicate symbol _srtp_create in:
    /Users/berndwindisch/Desktop/Sipper/Pods/MobileVLCKit-prod/MobileVLCKit-binary/MobileVLCKit.framework/MobileVLCKit(libvlc_srtp_la-srtp.o)
    /Users/berndwindisch/Desktop/Sipper/Pods/Vialer-pjsip-iOS/VialerPJSIP.framework/VialerPJSIP(srtp.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Seems like a conflict with MobileVLC....

Any help for me?

**Comment by bobvoorneveld** [comment]
seems that the two pods are in conflict with each other. I don't know MoblieVLC, have you tried to build it without that pod?

**Comment by HugoTheBoss** [comment]
I´ve compiled pjisp without SRTP, and it works! Can i use my compiled pjsip with vialer?

**Comment by bobvoorneveld** [comment]
I'm so sorry I haven't responded any sooner, but if you haven't found a solution at this time, please let us know. What you could do is create your own fork from https://github.com/VoIPGRID/Vialer-pjsip-iOS and use that pod as a source for your PJSIP version.

**Comment by bkr1989** [comment]
@bobvoorneveld  Hi bob i have my own modified PJSIP library.. can i integrate it into vailer....if so how....please help me out in this... i know you are not in this project now.. bt ur answer may help me

**Comment by redmerloen** [comment]
This issue is closed try to creatie your own fork of the project try it out
