### ISSUE TITLE
How to get Second Call Summary?

### ISSUE THREAD

**Issue by mital87** [VoIPGRID/VialerSIPLib#71]
@bobvoorneveld: How to get Second Call Summary (ie. call duration, mos, active codec etc.)? Please help me.

**Comment by spindleredmer** [comment]
When you look in the example app at the file [VSLTransferInProgressViewController.swift](https://github.com/VoIPGRID/VialerSIPLib/blob/develop/Example/VialerSIPLib/VSLTransferInProgressViewController.swift#L102)
There you see that the mos etc are gotten from the firstCall object. To do the same for the transferred call you can use the `secondCall` object. The mos, duration, codecs are properties on the VSLCall object.
```swift
secondCall!.connectDuration
secondCall!.mos
secondCall!.totalMBsUsed
secondCall!.activeCodec
```

**Comment by mital87** [comment]
@spindleredmer: Thanks...!!!

**Comment by mital87** [comment]
@spindleredmer & @bobvoorneveld : I have started **first call** connection. In **VSLCallViewController,** I press the transfer button & started **second call** connection. Right now my **first call** is on hold and the **second call** is active. now i am disconnecting my **second call**. I am not finding the **summary (ie. totalMBUsed, active codec, mos, call duration)** of the **second call** in **VSLSecondCallViewController**. Please help me ASAP.

**Comment by mital87** [comment]
@spindleredmer & @bobvoorneveld: How can i check, my last call is incoming or outgoing call? Is there any property in our library or not?

**Comment by spindleredmer** [comment]
Yes on the VSLCall object there is an property `incoming` this will be set to YES when a call is incoming.
When you check in the function prepare for segue in VSLSecondCallViewController, the secondCall is an instance of a VSLCall object. That should have the call summary.

**Comment by mital87** [comment]
@spindleredmer : How can i check, my last call is missed call?

**Comment by spindleredmer** [comment]
Currently that is not possible in the Example app to show missed calls.

**Comment by mital87** [comment]
@spindleredmer : **prepare for segue** function the in **VSLSecondCallViewController**. When i am disconnecting my second call, that time i have got segue of **VSLCallViewController**. Please guide me how can achieve my **goal(second call summary)**?

```
override func prepare(for segue: UIStoryboardSegue, sender: Any?)
{
  if let transferInProgressVC = segue.destination as? VSLTransferInProgressViewController
  {
  transferInProgressVC.firstCall = firstCall
  transferInProgressVC.secondCall = activeCall
  }
  else if let callVC = segue.destination as? VSLCallViewController
  {
  // The first call was disconnected, but second call in progress, so show second call as active call.
  
  if let call = firstCall, call.callState == .disconnected
  {
  callVC.activeCall = activeCall
  }
  }
  else
  {
  super.prepare(for: segue, sender: sender)
  }
}
```

**Comment by mital87** [comment]
@spindleredmer & @bobvoorneveld: Please guide me how can achieve my goal(second call summary)? I am awaiting for you reply.

**Comment by mital87** [comment]
@spindleredmer & @bobvoorneveld: Please guide me how can achieve my goal(second call summary)? I am awaiting for you reply.

**Comment by bobvoorneveld** [comment]
@mital87, You should be able to add another end of call screen that is very similar to the one already in the example app and make sure that the data presented on that screen uses the second call.
