### ISSUE TITLE
Using with CodePush

### ISSUE THREAD

**Issue by iclems** [VoIPGRID/VialerSIPLib#72]
Trying to build with Microsoft CodePush, I'm getting duplicate symbols: 
duplicate symbol _aes_encrypt
duplicate symbol _aes_decrypt
duplicate symbol _sha1

**Comment by iclems** [comment]
I've been able to go around this by not compiling within CodePush the aes_crypt and commenting parts of sha1. Not ideal but works ;-)

**Comment by bobvoorneveld** [comment]
We've no experience with CodePush, but it seems that CodePush uses some of the same encryption symbols als pjsip. Do you need any further help or can we close the issue?

**Comment by redmerloen** [comment]
I will close this issue. Is it still needed can reopen this.
