### ISSUE TITLE
Custom headers?

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [VoIPGRID/VialerSIPLib#73]
Is there any method to add custom headers to the call to be sent alongside when call starts?

**Comment by OrkhanAlikhanov** [comment]
I renamed [https://github.com/VoIPGRID/VialerSIPLib/blob/develop/Pod/Classes/VSLCall.m#L214]

**Comment by OrkhanAlikhanov** [comment]
I renamed [`startWithCompletion`](https://github.com/VoIPGRID/VialerSIPLib/blob/develop/Pod/Classes/VSLCall.m#L214) to `startWithHeaders`:
``` obj-c
- (void)startWithHeaders:(NSDictionary * _Nullable ) headers
                        :(void (^ _Nonnull)(NSError * _Nullable error))completion;
```
Changed only the [line 223](https://github.com/VoIPGRID/VialerSIPLib/blob/develop/Pod/Classes/VSLCall.m#L223) to:
``` obj-c
pj_status_t status = pjsua_call_make_call(
                                          (int)self.account.accountId,
                                          &sipUri,
                                          &callSetting,
                                          NULL,
                                          headers ? [self createMsgDataWithHeaders:headers] : NULL,
                                          (int *)&_callId);
```

The rest: 
``` obj-c
- (pjsua_msg_data *) createMsgDataWithHeaders:(NSDictionary *) headers {
    pjsua_msg_data *msg_data = malloc(sizeof(pjsua_msg_data));
    pjsua_msg_data_init(msg_data);
    pj_pool_t *pool;
    
    pj_caching_pool cp;
    pj_caching_pool_init(&cp, &pj_pool_factory_default_policy, 0);
    pool = pj_pool_create(&cp.factory, "call_tmp_header", 1000, 1000, NULL);
    
    pjsip_generic_string_hdr* hdr;
    
    for (NSString* key in headers) {
        NSString* value = [headers objectForKey: key];
        hdr = [self createHeaderAtPool:pool : key : value];
        pj_list_push_back(&msg_data->hdr_list, hdr);
        
    }

    pj_pool_release(pool);
    return msg_data;
}

- (pjsip_generic_string_hdr *) createHeaderAtPool:(pj_pool_t *) pool
                                                 :(NSString *)name
                                                 :(NSString *)value {
    pj_str_t hName = name.pjString;
    pj_str_t hValue = value.pjString;
    return pjsip_generic_string_hdr_create(pool, &hName, &hValue);
}
```
After that I cleaned syntax errors (due to method name and signature change) at the necessary places.


I don't know the PJSIP library very well and have never written in Obj-C therefore above code may have memory leak. I haven't tested it fully.

**Comment by bobvoorneveld** [comment]
please file a Pull Request and we'll look into it and integrate if the solution is workable.

**Comment by OrkhanAlikhanov** [comment]
This change will break up the projects that use `startWithCompletion` since I renamed it to `startWithHeaders` which takes additional parameter `headers`. Should I continue?.

**Comment by bobvoorneveld** [comment]
Could you create an extra method with your needs and factor out the common stuff in a private method that the old one still can call? In such way we don't have breaking changes.

**Comment by OrkhanAlikhanov** [comment]
Okay. I will look into this, but not very soon :)
