### ISSUE TITLE
crash app

### ISSUE THREAD

**Issue by masiiha** [VoIPGRID/VialerSIPLib#74]
@bobvoorneveld
<img width="852" alt="screen shot 2017-03-07 at 10 46 36 am" src="https://cloud.githubusercontent.com/assets/26216784/23645887/a6f812d0-0323-11e7-82bd-f82936c78f83.png">

14:54:38.939 os_core_unix.c !pjlib 2.5.5-svn for POSIX initialized
14:54:38.939 sip_endpoint.c  .Creating endpoint instance...
14:54:38.939          pjlib  .select() I/O Queue created (0x7fddbb030028)
14:54:38.940 sip_endpoint.c  .Module "mod-msg-print" registered
14:54:38.940 sip_transport.  .Transport manager created.
14:54:38.940   pjsua_core.c  .PJSUA state changed: NULL --> CREATED
WARNING: no real random source present!
assertion failed: file /Users/m.hajalian/Downloads/VialerSIPLib-develop-6/Example/VialerSIPLib/AppDelegate.swift, line 74
(lldb)

**Comment by bobvoorneveld** [comment]
looks like you haven't setup the SIPUSER proper. Did you use the correct credentials?

**Comment by masiiha** [comment]
Yes
I myself have used enterprise VoIP infrastructure

**Comment by bobvoorneveld** [comment]
Please step to the process of createAccount and check where the error is raised.

**Comment by masiiha** [comment]
I'm sorry
  Where the account creation page link?
