### ISSUE TITLE
Conference Call Audio

### ISSUE THREAD

**Issue by masiiha** [VoIPGRID/VialerSIPLib#76]
@bobvoorneveld 
How to make audio conferencing added to this App?

**Comment by bobvoorneveld** [comment]
This is not build in by us at this moment. This needs to be added to the library. PJSIP has functionality for it.
We haven't planned implementation for it, but are more than willing to help review any Pull Requests. Here is some documentation that might give you some pointers:
https://trac.pjsip.org/repos/wiki/Python_SIP/Media
It is in python, but finding the matching methods for Objective-c shouldn't be that difficult.

**Comment by masiiha** [comment]
Thank you very much @bobvoorneveld
