### ISSUE TITLE
Handle VoIP Notification With CallKit

### ISSUE THREAD

**Issue by mital87** [VoIPGRID/VialerSIPLib#79]
@bobvoorneveld : How can i handle **VoIP Notification** in **"didReceiveIncomingPushWithPayload"** delegate method? And How can i create **VSCall** object for **Incoming Call**?

**Comment by OrkhanAlikhanov** [comment]
After receiving voip push you just register with the call center (Freeswitch, asterisks or whatever) after registration the library will trigger the incoming call block (which you set) with the VSCall object.  

See sources of vialer-ios app for more information.

**Comment by mital87** [comment]
@OrkhanAlikhanov: i will put any lines of code in **"didReceiveIncomingPushWithPayload"** delegate methods or not for CallKIt Screen Appear?

**Comment by mital87** [comment]
@OrkhanAlikhanov : Thanks for the reply.

**Comment by barankaraoguzzz** [comment]
How did you do? What did you call in "didReceiveIncomingPushWithPayload" function? Can you help me pleas? @mital87

**Comment by bobvoorneveld** [comment]
We've build an APNS handler in our production app, see:

https://github.com/VoIPGRID/vialer-ios/blob/develop/Vialer/APNS/APNSHandler.m#L79

**Comment by bobvoorneveld** [comment]
And a class that handles the registration on the server of the pushes:

https://github.com/VoIPGRID/vialer-ios/blob/develop/Vialer/Middleware/Middleware.m

**Comment by barankaraoguzzz** [comment]
Thanks for the answers. @bobvoorneveld

**Comment by barankaraoguzzz** [comment]
i am sorry. How can I run classes that you write. I did not fully understand. Normally Do  PushKit and CallKit runing in appDelegate? Normally PushKit and CallKit do not work in appDelegate? How can i call this classes at AppDelegate?

**Comment by bobvoorneveld** [comment]
Please check our Vialer app how we initiate the classes and where they live.

**Comment by mital87** [comment]
@barankaraoguzzz : Please follow the below steps:

1) Please download **"APNSHandler"** from this link - (https://github.com/VoIPGRID/vialer-ios/blob/develop/Vialer/APNS/APNSHandler.m)
2) import **"APNSHandler"** in bridging file
3) Put this code in **"didFinishLaunchingWithOptions"**
`APNSHandler.shared().registerForVoIPNotifications()`
4) You will get token in **"didUpdatePushCredentials"** delegate method -- **"APNSHandler" file**
5)You will save the token on your database for push notification.
6) When VoIP notification will come, **"didReceiveIncomingPushWithPayload"**

**Comment by barankaraoguzzz** [comment]
i get it. I added APNSHandler class but ApnsHandler.java want to some class. These classes names are 

#import "APNSHandler.h"
#import "Middleware.h"
#import "Configuration.h"
#import "ColorConfiguration.h"
#import "SystemUser.h"
#import "MiddlewareRequestOperationManager.h"
#import "VoIPGRIDRequestOperationManager.h"
#import "ReachabilityManager.h"
#import "SIPUtils.h"
#import "NSString+SubString.h"
Finaly i need to add "vialer-swift" but i didn't find a "vialer-swift".
@bobvoorneveld  @mital87

**Comment by mital87** [comment]
@barankaraoguzzz: Simply put **"APNSHandler"** class in your project & comment on other import files & their methods. This is only for testing purpose only.

**Comment by barankaraoguzzz** [comment]
Thanks for helping @mital87
