### ISSUE TITLE
Push Middleware is not available

### ISSUE THREAD

**Issue by softwaremissinglink** [VoIPGRID/VialerSIPLib#8]
Right now the push middleware for asterisk link goes to 404. Is there any plan to release it soon?

**Comment by m-vellinga** [comment]
The middleware is nearly ready to be open source. Ill expect it to be within 2 weeks time. Ill keep you posted in this issue.

**Comment by m-vellinga** [comment]
Update as promised, the source code for the push middleware can be found here:

https://github.com/VoIPGRID/vialer-middleware

**Comment by ivivona** [comment]
Thanks!
