### ISSUE TITLE
Registration Dropped - switch from WiFi to 3G or change networks

### ISSUE THREAD

**Issue by mital87** [VoIPGRID/VialerSIPLib#80]
Is there any way to know my registration is dropped when i was switch from WiFi to 3G or change networks?

**Comment by mital87** [comment]
@bobvoorneveld, @spindleredmer: Please help me to resolve this issue. How can I get the notification when my registration is dropped due to any reason like switch from WiFi to 3G or change networks?

**Comment by mital87** [comment]
@bobvoorneveld, @spindleredmer: Please help me to resolve this issue.

**Comment by spindleredmer** [comment]
I think you need to implement an Notification manager that will detect when you switch networks.
When that happens that you need to update your registration.
The endpoint does start a network monitor, when a network switch happens you can listen for the notification `VSLNetworkMonitorChangedNotification` that is being fired. And handle on that in your application to trigger an update of your registration.
