### ISSUE TITLE
WWan Connection

### ISSUE THREAD

**Issue by mobilekonusarakogren** [VoIPGRID/VialerSIPLib#81]
we use the violersiplip for our project. App is when connected the 4G or 3G, connecting to sip server but data transfer is not provided. Is there anyone who can help me with this problem.

**Comment by spindleredmer** [comment]
I'm not quiet sure what yo mean?
What is not working with your integration?

**Comment by mobilekonusarakogren** [comment]
The problem is solved. The reason is our sip server because of the trial account. Thanks for your support.
