### ISSUE TITLE
Establish a call without the use of a tel number

### ISSUE THREAD

**Issue by csilouanos** [VoIPGRID/VialerSIPLib#82]
Hello!

I integrated the library in a project. What I have done over now is that:

1. I configured the library.
2. Created user's account. 
3. Tried to established a call.

As I can see from a [website](http://www.en.voipforo.com/SIP/SIP_addressing.php) that explains how SIP works (and in general what SIP is) it is acceptable to use this format user@ip_address as a URI. 

However in your library it seems that the phone number is required in order to establish a call. This is strange because even Android SDK provides you the capability to use **only** username and ip. 

Is there any method that I missed from the library to make a call only by using username and ip (i.e. user@ip_address)?

Thank you!

**Comment by Xedart** [comment]
Yeah just want to mention the same. I absolutely don't understand why you have focused on hone numbers as only way to make outbound calls. Or I missed something? Please, make it clear.

**Comment by spindleredmer** [comment]
This pod was written at first in mind our telephony platform in mind that uses only telephone numbers to call.
Be our guest to create a pull request that also makes the possibility to use the suggestion you make.

**Comment by armandzwan** [comment]
Has anyone tried to make this?

**Comment by redmerloen** [comment]
It has not been Made that you can make a call without a phonenumber. Because that is not what we use the pod for. If you want that functionaility write the code for it an add a pull request
