### ISSUE TITLE
Warning & Deprecation in Xcode 8.3

### ISSUE THREAD

**Issue by mital87** [VoIPGRID/VialerSIPLib#83]
Hi Team,

When I have built my project into Xcode 8.3 below warnings came. Please see the attached png. Please Update our project as soon as possible.

![warning Xcode 8 3](https://cloud.githubusercontent.com/assets/4548715/24689892/5ad499f2-19e7-11e7-967a-b39f66041fc5.png)

**Comment by redmerloen** [comment]
The deprecation warnings are now fixed with the newest version.
