### ISSUE TITLE
installaion Error

### ISSUE THREAD

**Issue by tarek903** [VoIPGRID/VialerSIPLib#84]
> 'MyTarget'  target has transitive dependencies that include static binares

to resolve this i must remove the 

> use_frameworks!

but if i remove it All my other pods thats written in swift won't Work. please help

**Comment by spindleredmer** [comment]
The Pod currently doesn't work with use_frameworks! on that is still a known issue. Because the dependecy vialer-pjsip-ios is still not compiled correctly to work swift only applications

**Comment by CedricSoubrie** [comment]
It means that right now we can't use your framework with classical pods such as Alamofire for example ?

**Comment by daholino** [comment]
@CedricSoubrie I solved the problem by using Carthage for Swift libraries and Cocoapods for VialerSIPLib. Maybe you could try this...

**Comment by tarek903** [comment]
I did the same @daholino
