### ISSUE TITLE
Codec Selection

### ISSUE THREAD

**Issue by barankaraoguzzz** [VoIPGRID/VialerSIPLib#85]
i am using this project for my calling project but i dont understand how can i choose custom codec.I do not understand how the project chooses the codec. Can you help me pleas?

**Comment by spindleredmer** [comment]
Currently it is still hardcoded in the Pod.
https://github.com/VoIPGRID/VialerSIPLib/blob/develop/Pod/Classes/VSLEndpoint.m#L382
There you can change your properties for the codec.
We are working on a solution to make it configurable.

**Comment by mital87** [comment]
@spindleredmer: Please add the functionality of codec selection.

**Comment by devwahii** [comment]
Hello, how i can set the "// G711 @"PCMU/8000/1" to be the default? Thanks.

**Comment by spindleredmer** [comment]
https://github.com/VoIPGRID/VialerSIPLib/blob/develop/Pod/Classes/VSLEndpoint.m#L413
`// G711
 @"PCMU/8000/1":      @0,`
set the @0 to a higher number then the others or do this for example. If you only want G711
`
priorities = @{
                      // G711
                       @"PCMU/8000/1":      @210,
                       // G711a
                       @"PCMA/8000/1":      @0,
                       // G722
                       @"G722/16000/1":     @0,
                       // iLBC
                       @"iLBC/8000/1":      @0,
                       // Speex 8 kHz
                       @"speex/8000/1":     @0,
                       // Speex 16 kHz
                       @"speex/16000/1":    @0,
                       // Speex 32 kHz
                       @"speex/32000/1":    @0,
                       // GSM 8 kHZ
                       @"GSM/8000/1":       @0,
                       };
`

**Comment by redmerloen** [comment]
Check the Example app on how to do codec configuration, this issue will be closed.
