### ISSUE TITLE
Registration Dropped - After 40 - 50 seconds when App is in Background

### ISSUE THREAD

**Issue by mital87** [VoIPGRID/VialerSIPLib#86]
@bobvoorneveld  & @spindleredmer: I am successfully **register** with my **Extension**. When my application is on **foreground**, my **registration** is **never dropped** but when my application is on **background(i.e. home screen / lock screen / another application)**, my **registration** is **drop within 40-50 seconds.** In this situation, i am not able to **receive incoming calls** as well. **Please help me to keep alive registration of my extension in background modes.** I am awaiting your valuable reply. Thanking You.

**Comment by mital87** [comment]
@bobvoorneveld & @spindleredmer: Please help me to resolve this issue.

**Comment by mital87** [comment]
@bobvoorneveld & @spindleredmer: Please help me to resolve this issue. I am awaiting your valuable reply. Thanking You.

**Comment by mital87** [comment]
@bobvoorneveld & @spindleredmer: Please help me to resolve this issue. I am awaiting your valuable reply. Thanking You.

**Comment by OrkhanAlikhanov** [comment]
That's normal behavior. The OS kind of kills the app if it is in the background. To tackle this issue, you have to have a middleware service that wakes the phone up (via VoIP push) before delivering the call to the callee.

**Comment by mital87** [comment]
@OrkhanAlikhanov: I am agreed with you. In background mode, the app will only alive with 3 mins after that it will be suspended. Suppose I have 2 extensions like 280 & 281. Now Ext. 280 is reachable (foreground mode) & Ext. 281 is unreachable (background mode). VoIP Notification service integrated into both extensions. Then Ext. 280 is calling to Ext. 281. Ext 280 got disconnected (Service unavailable) message in the first attempt because of Ext 281 unreachable. VoIP notification also received by Ext 281. Now Ext 281 is reachable. once again I have called on Ext 281 and i have got incoming call successfully. So please tell what can i do for the first attempt?

**Comment by OrkhanAlikhanov** [comment]
Your problem with the first attemp is that you send the VoIP push but you don't wait its delivery and you immediately try to connect ext. 280 with 281 (before 281 gets woken up and registers itself)


The solution is that you wait waking-up of ext 281 before trying to connect them. 

Take a look at [middleware repo](https://github.com/VoIPGRID/vialer-middleware).

**Comment by OrkhanAlikhanov** [comment]
Its like you have a call center like Asteriks or FreeSwitch. The call server receives a call by ext 280 which is to be forwarded to the ext 281.  The call center post to the middleware the id of calee (281) and *waits* the request finish before forwarding the call to the 281. On the middleware side, as soon as the middleware receives the request, it sends push VoIP to the extension (281), then enters into a loop and waits the I-have-woken-up message (which is sent by the ext. 281 after getting up). If the loop hits timeout (which you will probably hardcode) you respond back to the call center (which still waits the request response) that user didn't wake up. If, however, user gets woken up and timeout doesn't get hit, you respond back to the call center that user did wake up and the call center forwarda the call to the ext 281.

**Comment by mital87** [comment]
@OrkhanAlikhanov: Thanks for your reply. Now it is working for me.
