### ISSUE TITLE
How do I integrate video support for this library? 

### ISSUE THREAD

**Issue by bigboy90515** [VoIPGRID/VialerSIPLib#87]
How do I integrate video support for this library?
Hope to make a video calling ASAP.

**Comment by mital87** [comment]
@spindleredmer: When will you support of Video calling in our library?

**Comment by redmerloen** [comment]
eventually there will be video calling in the app but not in the near future

**Comment by jeremynorman89** [comment]
This is still not something that we have any plans to implement in the near future, we would absolutely welcome a pull request with this functionality though.
