### ISSUE TITLE
Please specify target machine

### ISSUE THREAD

**Issue by larcho** [VoIPGRID/VialerSIPLib#88]
I'm getting compiler errors like "Please specify target machine" continued by "PJ_HAS_PENTIUM" is not defined ...

Trying to build with iOS 10.3

**Comment by larcho** [comment]
I fixed the issue by adding the Preprocessor macro PJ_AUTOCONF=1 to the VialerSIPLib project.

**Comment by spindleredmer** [comment]
When you use cocoapods to install the library the Preprocessor macro should be added automatically.

**Comment by matteinn** [comment]
I'm facing the same issue using cocoapods, any suggestions?

**Comment by spindleredmer** [comment]
can you double check the PJ_AUTOCONF = 1 has been added to your project?

**Comment by avetyansos** [comment]
I have issue in config.h class #   error "Please specify target machine." #  error "PJ_HAS_PENTIUM is not defined!" #  error "PJ_IS_LITTLE_ENDIAN is not defined!" #  error "PJ_IS_BIG_ENDIAN is not defined!" in preprocessor macross PJ_AUTOCONF = 1 and the errors occurred. can you advise anything to solve the problem?

**Comment by bkr1989** [comment]
@redmerloen @bobvoorneveld Hi bob&redmerloen i have my own modified PJSIP library.. can i integrate it into vailer....if so how....please help me out in this... i know you are not in this project now.. bt ur answer may help me....my team added encryption functionality in PJSIp lib..

**Comment by ShlomieRottenberg** [comment]
@avetyansos I see your comment is old, but it has a few thumbs up so it seems to be an issue that people are having (myself included). For me, what fixed it was adding PJ_AUTOCONF = 1 to the project, not to the target (If you are using cocoapods, it will be the Pods project). 

To fix it I went to Pods project -> Build Settings -> Apple Clang - Preprocessing -> Preprocessor Macros, and added PJ_AUTOCONF to both debug & release. Hopefully this will help someone.

**Comment by willnaoosmith** [comment]
@ShlomieRottenberg yes it did.

> @avetyansos I see your comment is old, but it has a few thumbs up so it seems to be an issue that people are having (myself included). For me, what fixed it was adding PJ_AUTOCONF = 1 to the project, not to the target (If you are using cocoapods, it will be the Pods project).
> 
> To fix it I went to Pods project -> Build Settings -> Apple Clang - Preprocessing -> Preprocessor Macros, and added PJ_AUTOCONF to both debug & release. Hopefully this will help someone.

**Comment by mehdinourollah** [comment]
> @avetyansos I see your comment is old, but it has a few thumbs up so it seems to be an issue that people are having (myself included). For me, what fixed it was adding PJ_AUTOCONF = 1 to the project, not to the target (If you are using cocoapods, it will be the Pods project).
> 
> To fix it I went to Pods project -> Build Settings -> Apple Clang - Preprocessing -> Preprocessor Macros, and added PJ_AUTOCONF to both debug & release. Hopefully this will help someone.

It's not working for me ...still having that error....

**Comment by linus-komnick** [comment]
ShlomieRottenberg's answer works! But make sure not to include any spaces! It should be PJ_AUTOCONF=1 without spaces and in my case I had to **overwrite** the Preprocessor Macros (Debug and Release) so that PJ_AUTOCONF=1 is the only field.

**Comment by munibhassan** [comment]
Please help me with this error Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0035	#error directive: "Please specify target machine."	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	306	
Error	C1189	#error:  "Please specify target machine." (compiling source file Calls.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file AccountDlg.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file BaseDialog.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file AddDlg.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file AAOptionsDlg.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file CListCtrl_SortItemsEx.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file ClosableTabCtrl.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file addons.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file lib\Hid.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file Contacts.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file global.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file lib\MSIP.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file mainDlg.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file MessagesDlg.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file Dialer.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file microsip.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file Preview.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file RinginDlg.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file settings.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file SettingsDlg.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file ShortcutsDlg.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file StatusBar.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308	
Error	C1189	#error:  "Please specify target machine." (compiling source file Transfer.cpp)	microsip	C:\Users\hp\Downloads\New folder (13)\MicroSIP-3.21.3-src\pj\config.h	308
