### ISSUE TITLE
Can I get the instruction how to add VialerSIPLib manually to the Swift project?

### ISSUE THREAD

**Issue by tiana890** [VoIPGRID/VialerSIPLib#89]
Hello! 
Thank u for the lib. I try to add it to my Swift project via Cocoapods, but sadly I can not use it with #use_frameworks! directive. This issue has already been discussed. Perhaps you will add the instructions how to add it manually to the project? 
Thank u in advance.

**Comment by spindleredmer** [comment]
Hello, 
I'm sorry, i don't think it will work if you add it manually. Because the used sip library we created has not been compiled dynamic. If that issue is solved the #use_frameworks! directive will work.

**Comment by redmerloen** [comment]
I think in the newest version of cocoapods 1.5 you can use this pod.
Remove the `#user_frameworks!` from you Podfile
