### ISSUE TITLE
Header Route: 403 (Preload Route denied)

### ISSUE THREAD

**Issue by davidrivasro07** [VoIPGRID/VialerSIPLib#9]
Hi.

I just need to remove the Route header, is possible to do it?

Thanks.

**Comment by bobvoorneveld** [comment]
There is nothing build in to our library that makes that possible. You could try to find a way to make a fork and do something with:

http://www.pjsip.org/pjsip/docs/html/group__PJSIP__MSG__MSG.htm#ga3d81aa466417fe1da7041a5a662f6d55

We have no experience with changing the sip requests, so I think you need to do some extra searching to find an answer. If you come up with a good solution, please let us know!
