### ISSUE TITLE
Application Crash due to Video Codec

### ISSUE THREAD

**Issue by mital87** [VoIPGRID/VialerSIPLib#91]
@bobvoorneveld  & @spindleredmer: Is there any way to restrict Video codec in our library? In my server, Video Codec is active. So when I am going to call another extension that time my application will crash due to this. Please help me to resolve this issue as soon as possible.

**Comment by spindleredmer** [comment]
Do you only want to use the Video codec? There is not yet a configuration that the library uses video codec only. It is currently audio only, so your server needs to have the audio codec also available.

**Comment by mital87** [comment]
Okay. Thanks.
