### ISSUE TITLE
How to add Conference call in App?

### ISSUE THREAD

**Issue by manekdilip** [VoIPGRID/VialerSIPLib#93]
Does Lib support conference call? How can we integrate it?

**Comment by spindleredmer** [comment]
This lib doesn't yet support conference calling. It is on our roadmap to integrate it, but there isn't a date yet when we are going to build it.

**Comment by jeremynorman89** [comment]
There are no plans to implement this in the near future, we would absolutely welcome pull requests to add this feature.
