### ISSUE TITLE
Concerning BITCODE

### ISSUE THREAD

**Issue by nikkonikko** [VoIPGRID/VialerSIPLib#95]
Hi, nice library! 

It seems all the generated libraries have bitcode enabled. F.x. I run: 

otool -l Pods/Vialer-pjsip-iOS/VialerPJSIP.framework/VialerPJSIP  |  grep __LLVM

to confirm that. But I get this error and just can't figure out why:

> blabla/Pods/Vialer-pjsip-iOS/VialerPJSIP.framework/VialerPJSIP(darwin_dev.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor

Any idea how to solve this? 

I can't find the darwin_dev.c in the project, so I suppose it's Apple's build in file. Maybe I can disable some functionality in worst case to avoid the file. F.x. disable the VIDEO stuff?

Thanks in advance.

**Comment by spindleredmer** [comment]
This is the first time i have seen this error.
To disable the video the pjsip library needs to be recompiled without video

**Comment by redmerloen** [comment]
In Vialer-pjsip-ios 3.3.0 (just released) bitcode is enabled for PJSIP. So when this library updates to 3.3.0 of the vialer-pjsip-ios library i hope this will ben fixed.
